export const COLLEGE_NAMES = [
  "University Departments of Anna University  Chennai - CEG Campus  Sardar Patel Road  Guindy  Chennai 600 025",
  "University Departments of Anna University  Chennai - ACT Campus  Sardar Patel Road  Guindy  Chennai 600 025",
  "School of Architecture and Planning  Anna University Chennai 600025",
  "University Departments of Anna University  Chennai - MIT Campus  Chrompet  Tambaram Taluk  Chengalpattu District 600 044",
  "Annamalai University Faculty of Engineering and Technology Annamalai Nagar Cuddalore",
  "University College of Engineering  Villupuram  Kakuppam Villupuram District 605103",
  "University College of Engineering  Tindivanam  Melpakkam Tindivanam  Villupuram District 604001",
  "University College of Engineering  Arni  Arni to Devikapuram Road  Thatchur  Arni  Thiruvannamalai District 632326",
  "University College of Engineering  Kancheepuram Ponnerikarai Campus  NH4  Chennai-Bangalore Highway Karaipettai Village & Post  Kancheepuram District 631552",
  "Aalim Muhammed Salegh College of Engineering Muthapudupet  Avadi IAF  Chennai 600055",
  "Jaya Engineering College  Thirunindravur  Chennai 602024",
  "Jaya Institute of Technology  Kanchipadi Post  Thiruvallur- Tiruttani NH  Road  Thiruvallur District 631204",
  "Prathyusha Engineering college  Aranvoyalkuppam Thiruvallur District 602025",
  "R M D Engineering College (Autonomous)  Kavaraipettai Gummidipoondi  Thiruvallur District 601206",
  "R M K Engineering College (Autonomous)  Kavaraipettai Gummidipoondi  Thiruvallur District 601206",
  "S A Engineering College (Autonomous)  Thiruverkadu Chennai 600077",
  "Sri Ram Engineering College  Perumalpattu  Veppampattu (R S)  Thiruvallur District 602 024",
  "Sri Venkateswara College of Engineering and Technology Thirupachur  Thiruvallur District 631203",
  "Vel Tech Multi Tech Dr. Rangarajan Dr. Sakunthala Engineering College (Autonomous)  Avadi-Alamathi Road Chennai 600 062",
  "Velammal Engineering College (Autonomous)  Ambattur- Redhills Road  Chennai 600066",
  "Sri Venkateswara Institute of Science and Technology Kozhundalur  Thiruvallur District 631203",
  "Vel Tech High Tech Dr. Rangarajan Dr. Sakunthala Engineering College (Autonomous)  Avadi-Alamathi Road Chennai 600 062",
  "Gojan School of Business and Technology  Alamathi Chennai 600062",
  "SAMS College of Engineering and Technology Panappakkam  Chennai-Tirupathi Road  Uthukkottai Taluk Thiruvallur District 601102",
  "PMR Engineering College Adayalampattu  Chennai-600095",
  "J N N Institute of Engineering  Ushaa Garden  Kannigaipair Village  Uthukottai Taluk  Thiruvallur District 601102",
  "St. Peters College of Engineering and Technology  College Road  Avadi  Chennai 600 054",
  "R M K College of Engineering and Technology (Autonomous)  Puduvoyal  Gummidipoondi Taluk Thiruvallur District 601206",
  "Annai Veilankannis College of Engineering  Gandhi Road Nedungundram  Chennai 600048",
  "Annai Mira College of Engineering and Technology  Arcot Road  Arappakkam Village  Walaja Taulk  Ranipet District 632 517",
  "Jeppiaar Institute of Technology kunnam Village Sriperumpudur Taulk Kancheepuram District 631604",
  "St. Joseph's Institute of Technology (Autonomous)  Jeppiaar Nagar  Old Mahabalipuram Road (OMR)  Chennai 600119",
  "Sri Jayaram Institute of Engineering and Technology  51 N Elavur  58N  Natham  Gummidipoondi Taluk  Thiruvallur District 601201",
  "D M I College of Engineering  Palanchoor  Nazrethpet Chennai 602103",
  "Kings Engineering College  Sriperumpudur Taluk Kancheepuram District 602105",
  "Pallavan College of Engineering  Thimmasamudram Kancheepuram District 631502",
  "Panimalar Engineering College (Autonomous)  Nazarethpet Poonamallee  Chennai 602123",
  "Rajalakshmi Engineering College (Autonomous)  Thandalam Sriperumpudur Taluk  Kancheepuram District 602105",
  "Rajiv Gandhi College of Engineering  Nemili  Sriperumpudur Taluk  Kancheepuram District 602105",
  "S K R Engineering College  Poonamallee  Chennai 600123",
  "Saveetha Engineering College (Autonomous)  Thandalam Sriperumpudur Taluk  Kancheepuram District 602105",
  "Sree Sastha Institute of Engineering and Technology Chembarambakkam  Chennai 600103",
  "Sri Muthukumaran Institute of Technology  Near Mangadu Chennai 600069",
  "Sri Venkateswara College of Engineering (Autonomous) Post Bag No.1  Chennai-Bengaluru High Road  Pennalur Irungattukottai S.O.  Sriperumbudur Taluk  Kancheepuram District 602105",
  "Jaya College of Engineering and Technology  Parivakkam Poonamallee  Chennai 600056",
  "P B College of Engineering  Irungkattukottai  Sriperumpudur Taluk  Kancheepuram District 602117",
  "Loyola Institute of Technology  Mevaloorkuppam  B Village Palanchoor  Nazarethpet Post  Chennai 600123",
  "P T Lee Chengalvaraya Naicker College of Engineering and Technology  Oovery  Veliyur Post  Kancheepuram District 631 502",
  "Alpha College of Engineering  No.34  Udayavar Koil Street Poonamallee  Thirumazhisai  Chennai - 600124",
  "Indira Institute of Engineering and Technology  VGR Gardens  Pandur  Thiruvallur District 631203",
  "Apollo Engineering College  Mevaloorkuppam  Valarpuram Post  Sriperumpudur  Kancheepuram District 602105",
  "A R M College of Engineering and Technology Sattamangalam  Maraimalainagar  Chengalpattu District 603209",
  "Adhi College of Engineering and Technology Pazhayaseevaram  Madura Sankarapuram Village Kancheepuram District 631605",
  "Velammal Institute of Technology  Chennai-Kolkatta Highway  Panchetti Village  Ponneri Taluk  Thiruvallur District 601204",
  "G R T Institute of Engineering and Technology  GRT Mahalakshmi Nagar  Chennai-Tirupathi Highway  Tiruttani Taluk  Thiruvallur District 631209",
  "T J S Engineering College  Peruvoyal  Near Kavaraipettai Gummidipoondi Taluk  Thiruvallur District 601206",
  "Madha Institute of Engineering and Technology Erandamkattalai Village  Sadhananthapuram  Thandalam Post  Chennai  602101",
  "Mohammed Sathak A J College of Engineering  Old Mahabalipuram Road (OMR)  Egattur  Chengalpattu District 603103",
  "Anand Institute of Higher Technology  Old Mahabalipuram Road (OMR)  Kazhipattur  Chengalpattu District  603103",
  "Easwari Engineering College (Autonomous)  Ramapuram Chennai 600089",
  "Jeppiaar Engineering College  Old Mahabalipuram Road (OMR)  Chennai 600119",
  "Jerusalem College of Engineering (Autonomous) Narayanapuram  Pallikaranai  Chennai 600 100",
  "Meenakshi Sundararajan Engineering College Kodambakkam  Chennai 600024",
  "Misrimal Navajee Munoth Jain Engineering College  Rajiv Gandhi Salai (OMR)  Thorappakkam  Chennai 600096",
  "K C G College of Technology  Karappakkam  Chennai 600096",
  "Shree Motilal Kanhaiyalal (SMK)Fomra Institute of Technology  Old Mahabalipuram Road (OMR) Kelambakkam  Chengalpattu District 603103",
  "Sri Sivasubramaniya Nadar College of Engineering (Autonomous)  Kalavakkam  Old Mahabalipuram Road (OMR)  Chengalpattu District 603110",
  "Agni College of Technology  Old Mahabalipuram Road (OMR)  Thalambur Village  Chengalpattu District 603103",
  "St. Joseph's College of Engineering (Autonomous)  Old Mahabalipuram Road (OMR)  Chennai 600 119",
  "T.J Institute of Technology  Karapakkam  Chennai - 600097",
  "Thangavelu Engineering College  Karappakkam  Chennai 600097",
  "Central Institute of Petrochemicals Engineering and Technology (Formerly Central Institute of Plastics Engineering and Technology) (CIPET)  Guindy  Chennai 600032",
  "Dhanalakshmi Srinivasan College of Engineering and Technology  East Coast Road  Poonjeri  Chennai 603104",
  "Sri Sai Ram Institute of Technology (Autonomous)  West Tambaram  Chennai 600044",
  "St. Joseph College of Engineering  Trinity Campus  Nemili Sriperumpudur Taluk  Kancheepuram District 602105",
  "Sri Krishna Institute of Technology  Panapakkam  Padappai Chennai 601301",
  "Chennai Institute of Technology and Applied Research Sarathy Nagar Puthuper Village Kundrathur Chennai 600069",
  "Chennai Institute of Technology  Puduper Village Nandambakkam Post  Kundrathur  Chennai 600069",
  "Adhiparasakthi Engineering College  Melmaruvathur Chengalpattu District 603319",
  "Annai Teresa College of Engineering  Thirunavalur Kallakkurichi District 607204",
  "Dhanalakshmi College of  Engineering  Manimangalam Chennai 601301",
  "G K M College of  Engineering and Technology  Alappakkam- Mappedu Road  Chennai 600063",
  "I F E T College of Engineering  (Autonomous) Gangarampalayam  Villupuram District 605108",
  "Karpaga Vinayaga College of Engineering and Technology Palayanoor Post  Maduranthagam Taluk  Chengalpattu District 603308",
  "Madha Engineering College  Kundrathur  Chennai 600069",
  "Mailam Engineering College  Mailam  Villupuram District 604304",
  "Sri Venkateswaraa College of Technology  Sirukulathur Vadakkal Village  Pondur Post  Sriperumbudur Taluk Kancheepuram District 602105",
  "Prince Shri Venkateshwara  Padmavathy Engineering College  Ponmar  Chennai 600048",
  "T S M Jain College of Technology  Melur Village  Kallakurichi District 606201",
  "Jaya Sakthi Engineering College  Thirunindravur  Chennai 602024",
  "Sri Sai Ram Enginering College (Autonomous)  West Tambaram  Chennai 600044",
  "Tagore Engineering College  Rathnamangalam  Vandalur Post  Chennai 600048",
  "V R S College of Engineering and Technology  Arasur Villupuram District 607107",
  "SRM Valliammai Engineering College (Autonomous) Kattankulathur  Chennai 603203",
  "Asan Memorial College of Engineering and Technology Chengalpattu-603 001.",
  "Dhaanish Ahmed College of Engineering  Padappai  Chennai 601301",
  "Sri Ramanujar Engineering College  Vandalur  Kolappakkam Chennai 600127",
  "Sri Krishna Engineering College  Panappakkam  Padappai Chennai 601301",
  "E S COLLEGE OF ENGINEERING AND TECHNOLOGY  Chennai Trunk Road  Ayyankoilpattu  Villupuram District 605602",
  "Maha Bharathi Engineering College  A Vasudevanur Chinnasalem  Kallakurichi  District 606201",
  "New Prince Shri Bhavani College of Engineering and Technology  Vengaivasal Main Road  Gowrivakkam  Chennai 600073",
  "Rajalakshmi Institute of Technology  Irulapalayam Kuthampakkam Post  Kancheepuram District  Chennai 600124",
  "Surya Group of Institutions  GST Road  Vikravandi Village Villupuram District 605652",
  "A R Engineering College  Vadakuchipalayam Kappiyampuliyur Post  Villupuram District 605601",
  "Rrase College of Engineering  Padappai  Kancheepuram 601301",
  "Sree Krishna College of Engineering  Anaicut Post  Unnai Village  Vellore District 632101",
  "A K T Memorial College of Engineering and Technology Neelamangalam Village  Kallakurichi District 606202",
  "Prince Dr. K Vasudevan College of Engineering and Technology  Medavakkam-Mambakkam Road  Ponmar Chennai 600127",
  "Sri Rangapoopathi College of Engineering  Alampoondi Village  Gingee  Villupuram District 604151",
  "Saraswathy College of Engineering and Technology  NH-45 Main Road  Olakkur  Tindivanam Taluk  Villupuram District 604307",
  "Loyola ICAM College of Engineering and Technology  Loyola College Campus  Nungambakkam  Chennai 600034",
  "PERI Institute of Technology  Mannivakkam  West Tambaram  Chennai 600048",
  "Adhiparasakthi College of Engineering  Kalavai  Ranipet District 632506",
  "Arulmigu  Meenakshi Amman College of Engineering Vadamavandal Thiruvannamalai District 604410",
  "Arunai Engineering College  Mathur  Thiruvannamalai District 606603",
  "C Abdul Hakeem College of Engineering and Technology Melvisharam  Ranipet District 632509",
  "Ganadipathy Tulsiï¿½s Jain Engineering College Kaniyambadi  Vellore District 632102",
  "Meenakshi College of Engineering  Vembuliamman Koil Street  K K Nagar (West)  Chennai 600078",
  "Priyadarshini Engineering College  Vaniyambadi Post Thiruppattur District 635751",
  "S K P Engineering College  Thiruvannamalai District 606611",
  "Sri Balaji Chockalingam Engineering College  Arni Thiruvannamalai District 632317",
  "Sri Nandhanam College of Engineering and Technology Molagarampatti  Tirupattur  Vellore-635601",
  "Thanthai Periyar Government Institute of Technology Bagayam  Vellore District 632002",
  "Thirumalai Engineering College  Kilambi  Kancheepuram District 631551",
  "Thiruvalluvar College of Engineering and Technology Vandavasi  Thiruvannamalai District 604505",
  "Bharathidasan Engineering College  Nattrampalli Post Thiruppathur District 635854",
  "Kingston Engineering College  Chithoor Main Road Christianpet Village  Katpadi Taluk   Vellore District 632059",
  "Global Institute of Engineering and Technology  Bangalore- Chennai Highway  Melvisharam  Walajah Taluk  Ranipet District 632506",
  "Annamalaiar College of Engineering  Modaiyur Village Polur Taluk  Thiruvannamalai District 606902",
  "Podhigai College of Engineering and Technology Vinayakapuram  Adiyur Post  Tirupattur District 635601",
  "Sri Krishna College of Engineering  Tiruttani High Road Arakkonam  Ranipet District 631003",
  "Oxford College of Engineering  Venmani Village Karaipoondi Post  Polur Taluk  Thiruvannamalai District 606803",
  "Idhaya Engineering College for Women  Chinnasalem Kallakkurichi District 606201",
  "Government College of Technology (Autonomous) Thadagam Road  Coimbatore District 641013",
  "PSG College of Technology (Autonomous)  Peelamedu Coimbatore District 641004",
  "Coimbatore Institute of Technology (Autonomous)  Civil Aerodrome Post  Coimbatore District 641014",
  "Anna University Regional Campus - Coimbatore Maruthamalai Main Road  Navavoor Bharathiyar University Post  Somayampalayam  Coimbatore District 641046",
  "Sri Shanmugha College of Engineering and Technology Morur Bit II Village  Salem District 637304",
  "Muthayammal College of Engineering  Kakkaveri Post Namakkal District 637408",
  "N S N College of Engineering and Technology  Karur- Madurai NH7  Manalmedu  Karur District 639003",
  "K S R Institute for Engineering and Technology  Thokkavadi Namakkal District 637215",
  "Rathinam Technical Campus  Pollachi Road  Eachanari Coimbatore District 641021",
  "Aishwarya College of Engineering and Technology Errattaikaradu Paruvachi Post  Anthiyur (Via)  Bhavani Taluk Erode District 638312",
  "Asian College of Engineering and Technology  Asian College Road  Kondayampalayam  Near Saravanampatti Coimbatore District 641110",
  "Ganesh College of Engineering  Attur Main Road Mettupatti  Salem District 636111",
  "Sri Ranganathar Institute of Engineering and Technology Thudialur-Kovilpalay Road  Coimbatore District 641110",
  "Indian Institute of Handloom Technology  Foulke's Compound  Thillai Nagar  Salem District 636001",
  "Dhirajlal Gandhi College of Technology  Sikkanampatty (Opp. to Airport)  Omalur Taluk  Salem District 636309",
  "Shree Sathyam College of Engineering and Technology  NH- 47  Manjakkalpatti  Kuppanur Post  Sankari Taluk  Salem District 637301",
  "AVS College of Technology  Attur Main Road  Near AVS College of Arts & Science  Chinnagoundapuram  Salem District 636106",
  "Dhaanish Ahmed Institute of Technology  Pichanur Post (Near K G Chavadi)  Coimbatore District 641105",
  "Pollachi Institute of Engineering and Technology  Main Road  Poosaripatti  Pollachi Taluk  Coimbatore District 642205",
  "Arulmurugan College of Engineering  Karvazhi Road Thennilai Post  Karur District 639206",
  "V S B College of Engineering Technical Campus  Ealur Pirivu Solavampalayam Post  Coimbatore District 642109",
  "Suguna College of Engineering  Kalappatti Road  Civil Aerodrome Post  Coimbatore District 641014",
  "Arjun College of Technology  Chettiyakkapalayam Kinathukadavu  Coimbatore District 642120",
  "Vishnu Lakshmi College of Engineering and Technology Vellalore Post  Coimbatore District 641111",
  "Government College of Engineering  Chettikkarai Post Dharmapuri District 635704",
  "PSG Institute of Technology and Applied Research  Avinashi Road  Neelambur  Coimbatore 641062",
  "Adhiyamaan  College of Engineering (Autonomous)  Hosur Krishnagiri District 635109",
  "Annai Mathammal Sheela Engineering College  Erumapatty Post  Namakkal District 637013",
  "Government College of Engineering (Autonomous)  Bargur Krishnagiri District 635104",
  "K S Rangasamy College of Technology (Autonomous) Tiruchengode  Namakkal District 637215",
  "M Kumarasamy College of Engineering (Autonomous) Thalavapalayam  Karur District 639113",
  "Mahendra Engineering College (Autonomous) Mahendhirapuri  Mallasamudram  Namakkal District 637503",
  "Muthayammal Engineering College (Autonomous) Rasipuram  Namakkal District 637408",
  "Paavai Engineering College (Autonomous)   NH-7  Pachal Post  Namakkal District 637018",
  "P G P College of Engineering and Technology  Paramathi Post  Namakkal District 637207",
  "K S R College of Engineering (Autonomous)  Tiruchengode Namakkal District 637215",
  "S S M College of Engineering  Komarapalayam  Namakkal District 638183",
  "Government College of Engineering (Autonomous) Karuppur  Salem District 636011",
  "Sengunthar Engineering College  (Autonomous) Tiruchengode  Namakkal District 637205",
  "Sona College of Technology (Autonomous)  Suramangalam Post  Salem District 636005",
  "Vivekanandha College of Engineering for Women (Autonomous)  Sathinaickenpalayam  Elayampalayam Village  Kumaramangalam  Namakkal District 637205",
  "Er. Perumal Manimekalai College of Engineering  Near Koneripalli  Hosur  Krishnagiri District 635117",
  "V S B Engineering College(Autonomous)  Kovai Road  Karur District 639111",
  "Mahendra College of Engineering  Attur Road  Minnampalli Valapady  Salem District 636106",
  "Gnanamani College of Technology  Pachal Post  Namakkal District 637018",
  "The Kavery Engineering College  M Kalipatti Post  Mecheri Salem District 634456",
  "Selvam College of Technology  Pappanaickenpatti Post Namakkal District 637003",
  "Paavai College of Engineering  NH-7  Pachal Post  Namakkal District 637018",
  "Chettinad College of Engineering and Technology  NH-67 Trichy Main Road  Puliyur C F  Karur District 639114",
  "Mahendra Institute of Technology (Autonomous) Mahendhirapuri  Mallasamudram   Namakkal District 637503",
  "Vidyaa Vikas College of Engineering and Technology Varahoorampatti  Tiruchengode  Namakkal District 637 214",
  "Excel Engineering College (Autonomous)  NH-544  Salem Main Road  Pallakapalayam  Sankari West Post Komarapalayam Taluk  Namakkal District - 637303",
  "CMS College of Engineering  Emapuram Post  Namakkal District 637003",
  "A V S Engineering College  Military Road  Ammapet  Salem District 636003",
  "Mahendra Engineering College for Women Kumaramangalam  Namakkal District 637205",
  "R P Sarathy Institute of Technology  Poosaripatty Kadaympatty Taluk  Salem  Tamil Nadu-636305",
  "Jayalakshmi Institute of Technology, NH 7, Salem Main Rd, T.Kanigarahalli, Thoppur, Dharmapuri, Tamil Nadu 636352",
  "Varuvan Vadivelan Institute of Technology  Nallanahalli Dharmapuri District 636701",
  "P S V College of Engineeering and Technology  Mittapalli Balinayanapalli Post  Elathagiri  Krishnagiri District 635108",
  "Bharathiyar Institute of Engineering for Women Deviayakurichi  Attur Taluk  Salem District 636112",
  "Tagore Institute of Engineering and Technology Deviyakurichi  Attur Taluk  Salem District 636112",
  "J K K Nataraja College of Engineering and Technology Komarapalayam Amani  Thattankuttai Panchayat  Namakkal District 638183",
  "Annapoorana Engineering College (Autonomous)  Sankari Main Road  NH-47  Periaseeragapadi  Salem District 636308",
  "Christ The King Engineering College  Cecilia Gardens Chikkarampalayam Village  Coimbatore District 641104",
  "Jai Shriram Engineering College  Dharapuram Road Avinashi Palayam  Tiruppur District 638660",
  "AL-Ameen Engineering College (Autonomous)  Karundevan Palayam  Nanjai Uthukuli Post  Erode District 638104",
  "Knowledge Institute of Technology  KIOT Campus Kakapalayam Post  Salem District 637504",
  "Builders Engineering college  Nathakadaiyur  Erode Road Palayakottai Village  Kangeyam  Tiruppur District 638108",
  "V S A Group of Institutions  NH-47  Uthamasola Puram Post Salem District 636010",
  "Salem College of Engineering and Technology  Salem-Attur Main Road  NH-68  Mettupatty Perumapalayam  Salem District 636111",
  "Vivekanandha College of Technology for Women Sathinaickenpalayam  Elayampalayam Village Kumaramangalam  Namakkal District 637205",
  "Sree Sakthi Engineering College  Bettathapuram  Bilichi Village  Karamadai  Coimbatore District 641104",
  "Shreenivasa Engineering College  B Pallipatti  Bommidi Pappireddipatti Taluk  Dharmapuri District 635301",
  "Bannari Amman Institute of Technology (Autonomous) Sathyamanagalam  Erode District  638401",
  "Coimbatore Institute of Engineering and Technolgoy (Autonomous)  Narasipuram Post  Coimbatore District 641109",
  "CSI College of Engineering  Ketti  The Nilgiris 643215",
  "Dr. Mahalingam College of  Engineering and Technology (Autonomous)  Mackinaickenpatti Post  Pollachi Taluk Coimbatore District 642003",
  "Erode Sengunthar Engineering College (Autonomous) Thudupathi Post  Erode District 638057",
  "Hindusthan College of Engineering and Technology (Autonomous)  Othakkalmandapam Post  Coimbatore District 641032",
  "Government College of Engineering (Formerly Institute of Road and Transport Technology)  Vasavi College Post  Erode District 638316",
  "Karpagam College of Engineering (Autonomous) Othakkalmandapam  Coimbatore District 641032",
  "Kongu Engineering College (Autonomous)  Perundurai Erode District 638052",
  "Kumaraguru College of Technology (Autonomous) Chinnavedampatti Post  Coimbatore District 641006",
  "M P Nachimuthu M Jaganathan Engineering College Chennimalai  Erode District 638112",
  "Nandha Engineering College (Autonomous) Pitchandampalayam Post  Erode District 638052",
  "Park College of Engineering and Technology  Kaniyur Coimbatore District 641659",
  "Sasurie College of Engineering  Vijayamangalam  Tiruppur District 638056",
  "Sri Krishna College of Enginering and Technology (Autonomous)   Kuniamuthur  Coimbatore District 641008",
  "Sri Ramakrishna Engineering College (Autonomous) Vattamalaipalayam  Coimbatore District 641022",
  "Tamilnadu College of Engineering  Karumathampatti Post Coimbatore District 641659",
  "Sri Krishna College of Technology (Autonomous) Kovaipudur Post  Coimbatore District 641042",
  "Velalar College of Engineering and Technology (Autonomous)  Thindal Post  Erode District 638012",
  "Sri Ramakrishna Institute of Technology (Autonomous) Pachapalayam  Coimbatore District 641010",
  "SNS College of Technology (Autonomous)  Kalappatti Post Coimbatore District 641035",
  "Sri Shakthi Institute of Engineering and Technology (Autonomous)  L&T Bye-Pass  Venkitapuram Post Comibatore District 641062",
  "Nehru Institute of Engineering and Technology Thirumalayampalayam Post  Coimbatore District 641105",
  "R V S College of Engineering and Technology Kannampalayam  Sulur  Coimbatore District 641402",
  "Info Institute of Engineering  Sarkar Samakulam Coimbatore District 641107",
  "Angel College of Engineering and Technology  P.K.Palayam Ugayanur Village  Tirupur District 641 665",
  "SNS College of Engineering (Autonomous)  Sathy Main Road Kurumbapalayam Post  Coimbatore District 641107",
  "Karpagam Institute of Technology  Seerapalayam Village L&T By pass Road  Coimbatore District 641021",
  "Dr. N G P Institute of Technology  Kalapatti Road Coimbatore District 641035",
  "Sri Sai Ranganathan Engineering College Zahirnaickenpalayam Village  Viraliyur Post  Thondamuthur Via  Coimbatore District 641109",
  "Sri Eshwar College of Engineering (Autonomous) Kondampatti Post  Vadasithur (Via)  Kinathukadavu Coimbatore District 641202",
  "Hindusthan Institute of Technology (Autonomous) Othakkalmandapam  Coimbatore District 641032",
  "P A College of Engineering and Technology (Autonomous) Palladam Road  Pollachi  Coimbatore District 642002",
  "Dhanalakshmi Srinivasan College of Engineering (CBE) NH47  Palakkad Main Road  Navakkarai Post  Near Nandhi Temple  Coimbatore District 641105",
  "Adithya Institute of Technology  Kurumbapalayam Village Coimbatore District 641107",
  "Kathir College of Engineering  Neelambur  Avinashi Road Coimbatore District 641062",
  "Shree Venkateshwara Hi-Tech Engineering College Othakuthirai  K Mettupalayam Post  Gobichettipalayam Erode District 638455",
  "Surya Engineering College  Mettukadai  Kathirampatti Post Erode District 638107",
  "Easa College of Engineering and Technology  NH-47 Coimbatore-Palakkad Main Road  Navakarai Post Coimbatore District 641105",
  "KIT - Kalaignar Karunanidhi Institute of Technology (Autonomous)  Kannampalayam  Coimbatore District 641402",
  "KGISL Institute of Technology  KGISL Campus  Thudiyalur Road  Saravanampatti  Coimbatore District 641035",
  "Nandha College of Technology  Pitchandampalayam Post Erode District 638052",
  "PPG Institute of Technology  Vilankurichi Village Coimbatore District 641035",
  "Nehru Institute of Technology  Thirumalayampalayam Post Coimbatore District 641105",
  "J K K Munirajah College of Technology  T N Palayam  Gobi Taluk  Erode District 638506",
  "United Institute of Technology  Gadalore Village Perianaickenpalayam  Coimbatore District 641020",
  "Jansons Institute of Technology  Karumathampatty  Somaur Coimbatore District 641659",
  "Akshaya College of Engineering and Technology Kinathukadavu  Coimbatore District 642109",
  "K P R Institute of Engineering and Technology (Autonomous)  Kollupalayam Village  Arasur Panchayat Coimbatore District 641407",
  "SRG Engineering College  Aniyapuram Post  Namakkal District 637017",
  "Park College of Technology  Prema Ravi Nagar Karumathampatti  Coimbatore - 641 659",
  "J C T College of Engineering and Technology  Pichanur Coimbatore District 641105",
  "Studyworld College of Engineering  Madukarai Post Coimbatore - 641 105.",
  "C M S College of Engineering and Technology Appachigoundenpathy  Kumittipathi Post  Coimbatore District 641032",
  "R V S Technical Campus-Coimbatore  Kumaran Kottam Campus   Kannampalayam  Sulur  Coimbatore District 641 402",
  "University College of Engineering  Tiruchirappalli (Bharathidasan Institute of Technology)  Tiruchirappalli District 620024",
  "University College of Engineering  Ariyalur  Kathankudikadu Village  Thelur Post  Ariyalur District 621704",
  "University College of Engineering  Thirukkuvalai Nagappattinam District 610204",
  "University College of Engineering  Panruti  Chennai- Kumbakonam Highway  Panikkankuppam  Panruti Cuddalore District 607106",
  "University College of Engineering  Pattukkottai  ECR Road Rajamadam  Pattukkottai Taluk  Thanjavur District 614701",
  "Krishnasamy College of Engineering and Technology  S Kumarapuram  Cuddalore District 607109",
  "C K College of Engineering and Technology Chellangkuppam  Cuddalore District 607003",
  "Sri Ramakrishna College of Engineering  Sri Saradha Nagar NH-45  Perambalur District  621113",
  "K S K College of Engineering and Technology  Thanjavur Main Road  Darasuram  Kumbakonam  Thanjavur District 612702",
  "Surya College of Engineering  Konalai  Tiruchirappalli District 621132",
  "Arifa Institute of Technology(Formly Haji sheik Ismail Engineering College)  Esanoor  Keelaiyur Post  Thirukkuvalai Taluk  Nagapattinam District 611103",
  "Ariyalur Engineering College  NH-227  Trichy-Chithambaram NH  Karuppur-Senapathy Post  Ariyalur District 621707",
  "Government College of Engineering  Gandarvakottai Road Sengipatti  Thanjavur District 613402",
  "Government College of Engineering  Srirangam Sethurappatti  Tiruchirappalli District 620012",
  "Nelliandavar Institute of Technology  Nerunjikorai Village Pudhupalayam  Ariyalur Taluk  Ariyalur District 621704",
  "K Ramakrishnan College of Technology (Autonomous) Kariyamanickam Road  Samayapuram  Manachanallur Taluk Tiruchirappalli District 621112",
  "Sir Issac Newton College of Engineering and Technology Anthanapeetai Post  Papakoil  Nagappattinam District 611102",
  "Star Lion College of Engineering and Technology Manankorai Main Road  Manankorai Village  Thanjavur District 614206",
  "OASYS Institute of Technology   Pulivalam Village  Musiri Taluk  Tiruchirappalli District 621006",
  "M.A.M. School of Engineering  Siruganur  Tiruchirappalli District 621105",
  "SRM TRP Engineering College  Irungalur  Manachanallur Taluk  Tiruchirappalli District 621105",
  "A V C College of Engineering  Mannampandal Post MayiladuthuraiDistrict 609305",
  "Anjalai Ammal Mahalingam Engineering College  Kovilvenni Thiruvarur District 614403",
  "Arasu Engineering  College  Chennai Main Road Kumbakonam  Thanjavur District 612501",
  "Dhanalakshmi Srinivasan  Engineering College (Autonomous)  Thuraiyur Road  Perambalur District 621212",
  "E G S Pillay  Engineering College (Autonomous) Nagapattinam District 611002",
  "J J College of Engineering and Technology Poolankulathupatti Post  Thiruchirappalli District 620009",
  "Jayaram College of Engineering and Technology Karattampatti  Pagalavadi Po Thuraivur  Trichy-621014",
  "Kurinji College of Engineering and Technology  Manapparai Tiruchirappalli District 621307",
  "M.A.M. College of Engineering  Siruganur  Tiruchirappalli District 621105",
  "M I E T Engineering College  Trichy-Pudukkottai Road Tiruchirappalli District 620007",
  "Mookambigai College of Engineering  Keeranur Pudukkottai District 622502",
  "Oxford Engineering College, Karumandapam, Pirattiyur, Trichy 620 009",
  "P R Engineering College  Vallam  Thanjavur District 613403",
  "Pavendar Bharathidasan College of Engineering and Technology  Pudukkottai Main Road  Tiruchirappalli District 622515",
  "Roever Engineering College  Elambalur  Perambalur District 621212",
  "Saranathan College of  Engineering  Panjappur Tiruchirappalli District  620012",
  "Trichy Engineering College  Konalai  Tiruchirappalli District 621132",
  "A R J College of Engineering and Technology  Mannargudi Taluk  Thiruvarur District 614001",
  "Dr.Navalar Nedunchezhiyan College of Engineering Raja Nagar Vaithiyanathapuram tholudur  Cuddalore-606303",
  "St. Joseph's College of Engineering and Technology  Elupatti Village  Rawaspatti Post  Thanjavur District 613403",
  "Kongunadu College of Engineering and Technology (Autonomous)  Tholurpatti  Thottiyam  Tiruchirappalli District 621215",
  "M.A.M. College of Engineering and Technology  Trichy- Chennai Trunk Road  Siruganur  Tiruchirappalli District 621105",
  "K Ramakrishnan College of Engineering (Autonomous) Kariyamanickam Road  Samayapuram  Manachanallur Taluk Tiruchirappalli District 621112",
  "Indra Ganesan College of Engineering  Madurai Main Road Manikandam  Tiruchirappalli District 620012",
  "Parisutham Institute of Technology and Science  Ring Road Nanjikottai  Thanjavur District 613006",
  "CARE College of Engineering   Thayanoor Village Kuttappatti  Srirangam Taluk  Tiruchirappalli District 620009",
  "M R K Institute of Technology  Nattarmangalam Village Kattumannarkoil  Cuddalore District 608306",
  "Shivani Engineering College  Trichy-Dindigul NH Road Poolangulathupatti  Tiruchirappalli - 620009",
  "Imayam College of Engineering  Kannanur  Thuraiyur Tiruchirappalli District 621206",
  "Mother Terasa College of Engineering and Technology Mettusalai Post and Taluk  Pudukkottai District 622102",
  "Vandayar Engineering College  Pulavarnatham Post Mariamman Koil (Via)  Thanjavur District 613001",
  "Annai College of Engineering and Technology  Anakudi Road Kovilacheri  Kumbakonam  Thanjavur District 612503",
  "Vetri Vinayaha College of Engineering and Technology Namakkal-Trichy Main Road  Tholurpatti Village  Thottiam Tiruchirappalli District 621215",
  "Sri Bharathi Engineering College for Women  Kaikkuruchi Village  Alangudi Taluk  Pudukkottai District 622303",
  "Mahath Amma Institute of Engineering and Technology (MIET)  Ariyur  Annavasal Road  Illupur Taluk  Pudukkottai District 622101",
  "As-Salam College of Engineering and Technology Thirumangalakudi  Aduthurai  Thiruvidaimaruthur Thanjavur District 612102",
  "Meenakshi Ramaswamy Engineering College  Trichy Main Road   Thathanur  Udayarpalayam  Ariyalur District 621804",
  "Sembodai Rukmani Varatharajan Engineering College Sembodai Village  Vedaraniam  Nagappattinam District 614820",
  "St. Anne's College of Engineering and Technology Anguchettypalayam  Siruvathur Post  Panruti  Cuddalore District 607110",
  "Kings College of Engineering  Punalkulam  Pudukkottai District 613303",
  "Mount Zion College of Engineering and Technology Pilivalam Post  Pudukkottai District 622507",
  "Shanmuganathan Engineering College  Pillivalam Post Pudukkottai District 622507",
  "Sudharsan Engineering College  Sathiyamangalam Post Pudukkottai District 622501",
  "M N S K College of Engineering  Vallathirakkottai Post Pudukkottai District 622305",
  "Chendhuran College of Engineering and Technology Madurai Road  Lenavilakku  Pilivalam Post  Pudukkottai - 622 507",
  "Anna University Regional Campus - Tirunelveli  Trivandrum Road  Palayamkottai  Tirunelveli District 627007",
  "University College of Engineering  Nagercoil  Nagercoil Industrial Estate  Konam  Kanyakumari District 629004",
  "University V.O.C. College of Engineering  Thoothukudi  Near V.O.C. College  Millerpuram  Thoothukudi District 628008",
  "Thamirabharani Engineering College  Chathirampudukulam Village  Thatchanallur  Tirunelveli District 627358",
  "Rohini College of Engineering & Technology  Anjugramam- Kanyakumari Main Road  Palkulam  Variyoor Post Kanyakumari District 629401",
  "Stella Mary's College of Engineering  Arunthengan Vilai Azhikal Post  Kanyakumari District 629202",
  "Universal College of Engineering and Technology  Anbagam Campus  Radhapuram Road  Vallioor  Tirunelveli District 627117",
  "Renganayagi Varatharaj College of Engineering  Salvarpatti Sivakasi  Virudhunagar District 626128",
  "Lourdes Mount College of Engineering and Technology Marthandam-Karungal Road  Chundavilai  Mullanganavilai Nattalam Post  Kanyakumari District 629195",
  "Ramco Institute of Technology  North venganallur Village Krishnapuram Panchayat  Rajapalayam  Virudhunagar District 626117",
  "AAA College of Engineering and Technology  Kamarajar Educational Road  Amathur Village  Sivakasi  Virudhunagar District 626005",
  "Good Shepherd College of Engineering and Technology Maruthamparai  Kanyakumari District 629101",
  "V V College of Engineering  Arasoor Village  Idaichivilai Post Santhakulam Taluk  Thoothukudi District 628656",
  "Sethu Institute of Technology (Autonomous)  Kariapatti Post  Virudhunagar District 626115",
  "Sun College of Engineering and Technology Ammandivilai & Post  Kanyakumari District - 62920",
  "Maria College of Engineering and Technology  Attoor Puliyamoodu Junction  Thiruvattar Post  Kanyakumari District 629177",
  "MAR Ephraem College of Engineering & Technology Malankara Hills  Elavuvillai  Marthandam  Kanyakumari District 629171",
  "M E T Engineering College  Mogals Garden  Thovalai Village Aralvaimozhi Town Panchayat  Thovalai  Kanyakumari District 629304",
  "Grace College of Engineering  Chandy Nagar  Mullakkadu Thoothukudi District 628005",
  "St. Mother Theresa Engineering College  Vagaikulam Thoothukudi District 628102",
  "Holy Cross Engineering College  Vagaikulam  Sri Mulakarai Srivaikuntam   Thoothukudi District 628851",
  "Sivaji College of Engineering and Technology  Manivilla Palulai Panchayat  Vilavancode  Kanyakumari District 629171",
  "Unnamalai Institute of Technology  Ayyaneri  Kovilpatti Thoothukudi District 628502",
  "Satyam College of Engineering and Technology, Satyam Nagar, Aralvoimozhi, Kanyakumari-629301",
  "Arunachala College of Engineering for Women  Thanka Gardens  Manavilai  Vellichanthai  Nagercoil  Kanyakumari District 629203",
  "D M I Engineering College  Aralvaimozhi Village  Thovalai Kanyakumari District 629301",
  "PSN Institute of Technology and Science Melathediyoor Tirunelveli-627 152",
  "C S I Institute of Technology  Thovalai  Kanyakumari District 629302",
  "CAPE Institute of Technology  Levingipuram  Tirunelveli District 627114",
  "Dr. Sivanthi Aditanar College of Engineering  Tiruchendur Thoothukudi District 628215",
  "Francis Xavier Engineering College (Autonomous) Vannarpettai  Tirunelveli District 627003",
  "Jayamatha Engineering College  Aralvaimozhi  Kanyakumari District",
  "Jayaraj Annapackiam CSI College of Engineering  Nazareth Thoothukudi District 628617",
  "Kamaraj College of Engineering and Technology (Autonomous)  Virudhunagar District 626001",
  "Mepco Schlenk Engineering College (Autonomous) Sivakasi  Virudhunagar District 626005",
  "Nellai College of Engineering, Maruthakulam Post Tirunelveli District 627151",
  "National  Engineering College (Autonomous)  Kovilpatti Thoothukudi District 628503",
  "PSN College of Engineering and  Technology (Autonomous) Melathediyoor  Tirunelveli-627 152",
  "P S R  Engineering College (Autonomous) Appayanaickenpatti  Sevalpatty  Virudhunagar District 626140",
  "PET Engineering College  Vallioor Post  Tirunelveli District 627117",
  "S Veerasamy Chettiar College of  Engineering and Technology  Puliangudi Post  Tenkasi District 627855",
  "Sardar Raja College of Engineering  Alangulam  Tenkasi District 627808",
  "SCAD College of Engineering and Technology Cheranmahadevi  Tirunelveli District 627414",
  "Sree Sowdambika  College of Engineering  Aruppukkottai Taluk  Virudhunagar District 626134",
  "St. Xavier's Catholic College of Engineering (Autonomous) Chunkankadai  Nagercoil  Kanyakumari District 629807",
  "AMRITA  College of Engineering and Technology Erachakulam Post  Kanyakumari District 629902",
  "Government College of Engineering  Tirunelveli District 627007",
  "Dr. G U Pope College of Engineering  Sawyerpuram Thoothukudi District  628251",
  "Infant Jesus College of Engineering  Thoothukudi Highway (NH7/A)  Thoothukudi District 628851",
  "Narayanaguru College of Engineering  Manjalumoodu Kanyakumari District 629151",
  "Udaya School of Engineering,   Ammandivilai Post, Kanyakumari District 629204",
  "Arul Tharum VPMM College of Engineering and Technology (Formerly V.P.Muthaiah Pillai Meenakshi Ammal Engineering College for Women)  Krishnakoil Virudhunagar- 626 190",
  "Einstein College of Engineering  Seethaparpanallur Tirunelveli District 627012",
  "Ponjesly College of  Engineering  Vettornimadam Post Nagercoil  Kanyakumari District 629003",
  "Vins Christian College of Engineering  Chunkankadai Post Nagercoil  Kanyakumari District  629807",
  "Lord Jegannath College of Engineering and Technology Kumarapuram  Thoppur Post  Kanyakumari District 629402",
  "Marthandam College of Engineering & Technology Kuttakuzhi  Veeyanoor Post  Kanyakumari District 629177",
  "Noorul Islam College of Engineering and Technology, No.10/47, Haji Manzil Main Road, Thuckalay, Kanyakumari 629175",
  "PSN Engineering College  Melathediyoor  Tirunelveli District 627152",
  "Bethlahem Institute of Engineering  Karungal  Kanyakumari District 629157",
  "Loyola Institute of Technology and Science  Loyola Nagar   P B No.2  Thovalai  Kanyakumari District 629302",
  "J P College of Engineering  College Road  Ayakudy  Tenkasi Taluk  Tenkasi District 627852",
  "P.S.R.R College of Engineering  Appayanaickenpatti Sevalpatti  Virudhunagar District 626140",
  "Sri Vidya College of Engineering and Technology  Sivakasi Main Road  P Kumaralinapuram  Virudhunagar District 626005",
  "Mahakavi Bharathiyar College of Engineering and Technology  Vasudevanallur  Tenkasi District 627758",
  "Annai Vailankanni College of Engineering  Pothaiyadi Salai Pottalkulam  Azhagappapuram  Kanyakumari District 629401",
  "Thiagarajar College of Engineering (Autonomous) Tirupparankundram  Madurai District 625015",
  "Government College of Engineering Melachokkanathapuram  Bodinayakkanur  Theni District 625582",
  "Anna University Regional Campus - Madurai  Kanyakumari National Highway  Keelakuilkudi  Madurai District 625019",
  "Central Electrochemical Research Institute CECRI)  Karaikudi Sivagangai District 630006",
  "University College of Engineering  Ramanathapuram Pullangudi  Ramanathapuram District 623513",
  "University College of Engineering  Dindigul  Mangarai Pirivu Reddiyarchathiram  Dindigul District 624622",
  "Sri Raajaraajan College of Engineering & Technology Amaravathi Village  Amaravathi Pudur Post  Karaikudi Sivagangai District 630301",
  "SSM Institute of Engineering and Technology  Kuttathupatti Village  Sindalaigundu Post  Dindigul District 624002",
  "Vaigai College of Engineering  Therkutheru  Melur Taluk Madurai District 625122",
  "Karaikudi Institute of Technology and Karaikudi Institute of Management  KIT & KIM Technical Campus  Keeranipatti Thalakkuvur  Karaikudi  Sivagangai District 630307",
  "Mangayarkarasi College of Engineering  First Street Mangayarkarasi Nagar  Paravai  Madurai District 625402",
  "Christian College of Engineering and Technology Oddanchatram  Dindigul District 624619",
  "N P R College of Engineering and Technology  Natham Dindigul District 624401",
  "SRM Madurai College for Engineering and Technology (Formely Madurai Institute of Engineering and Technology), Pottapalayam Village  Manamadurai Taluk  Sivagangai District 630611",
  "Veerammal Engineering College  PVP Nagar  K.Singrakottai Dindigul-624708",
  "R V S Educational Trust's Groups of Institutions, (Integrated Campus)  N Paraipatti Post  Vedasandur Taluk  Dindigul District 624005",
  "Nadar Saraswathi College of Engineering and Technology Vadupudupatti  Annanji Post  Theni District 625531",
  "Alagappa Chettair Government College of Engineering and Technology (Autonomous)  Karaikudi  Sivagangai District 630004",
  "Bharath Niketan Engineering College Thimmarasanaickanoor  Aundipatti  Theni District 625536",
  "K L N College of Engineering (Autonomous)  Pottapalayam Sivagangai District 630611",
  "Mohamed Sathak Engineering College  Kilakarai Ramanathapuram District 623806",
  "P S N A Colllege of Engineering and Technology (Autonomous),  Dindigul District 624622",
  "P T R College of Engineering and Technology Thanapandiyan Nagar  Austinpatty Post  Madurai District 625008",
  "Pandian Saraswathi Yadav Engineering College Thirumansolai Post  Sivagangai District 630 561",
  "R V S College of Engineering  N Paraipatti Post  Dindigul District 624005",
  "Solamalai College of Engineering  Veerapanjan  Madurai District 625020",
  "SACS-M A V M M Engineering College  Kidaripatty Post Madurai District 625301",
  "St. Michael College of Engineering and Technology Kalayarkoil  Sivagangai District 630551",
  "Syed Ammal Engineering College  Achuthan Vayal Post Ramanathapuram District 623502",
  "Ganapathy Chettiar College of Engineering and Technology Melakavanur Post  Paramakudi  Ramanathapuram District 623706",
  "SBM College of Engineering and Technology  Thamaraipady T N Paraipatti Pirivu  Dindigul District 624005",
  "Fatima Michael College of Engineering and Technology Sengottai Village  Sivagangai Main Road  Madurai District 625020",
  "Ultra College of Engineering and  Technology  Kodikulam  1 Bit Village  Madurai-Chennai Highway  Madurai District 625104",
  "Velammal College of Engineering and Technology  Madurai District 625009",
  "Theni Kammavar Sangam College of Technology  Theni Main Road  Koduvillarpatti Post  Theni District 625534",
  "Latha Mathavan Engineering College  Kidaripatti Post Alagarkoil (Via)  Melur Taluk  Madurai District 625301",
];

export const UNIQUE_COURSE_NAMES = [
  "BIO MEDICAL ENGINEERING  (SS)",
  "CIVIL  ENGINEERING",
  "COMPUTER SCIENCE AND ENGINEERING (SS)",
  "COMPUTER SCIENCE AND ENGINEERING",
  "ELECTRONICS AND COMMUNICATION ENGINEERING",
  "ELECTRICAL AND ELECTRONICS ENGINEERING",
  "ELECTRONICS AND COMMUNICATION ENGINEERING (SS)",
  "GEO INFORMATICS",
  "INDUSTRIAL ENGINEERING",
  "INFORMATION TECHNOLOGY (SS)",
  "MATERIAL SCIENCE AND ENGINEERING (SS)",
  "MECHANICAL ENGINEERING",
  "MINING ENGINEERING",
  "MANUFACTURING ENGINEERING",
  "PRINTING AND PACKING TECHNOLOGY",
  "CIVIL ENGINEERING (TAMIL MEDIUM)",
  "MECHANICAL ENGINEERING (TAMIL MEDIUM)",
  "APPAREL TECHNOLOGY (SS)",
  "CHEMICAL  ENGINEERING",
  "CHEMICAL  ENGINEERING (SS)",
  "CERAMIC TECHNOLOGY (SS)",
  "FOOD TECHNOLOGY (SS)",
  "INDUSTRIAL BIO TECHNOLOGY",
  "INDUSTRIAL BIO TECHNOLOGY (SS)",
  "LEATHER TECHNOLOGY",
  "PHARMACEUTICAL TECHNOLOGY (SS)",
  "PETROLEUM ENGINEERING AND TECHNOLOGY (SS)",
  "TEXTILE TECHNOLOGY",
  "B.Plan",
  "AERONAUTICAL ENGINEERING",
  "ARTIFICIAL INTELLIGENCE AND DATA SCIENCE (SS)",
  "AUTOMOBILE ENGINEERING",
  "ELECTRONICS AND INSTRUMENTATION ENGINEERING",
  "PRODUCTION ENGINEERING",
  "ROBOTICS AND AUTOMATION (SS)",
  "RUBBER AND PLASTIC TECHNOLOGY",
  "COMPUTER SCIENCE AND ENGINEERING (ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING)",
  "COMPUTER SCIENCE AND ENGINEERING (DATA SCIENCE)",
  "CIVIL AND STRUCTUTURAL ENGINEERING",
  "INFORMATION TECHNOLOGY",
  "MECHANICAL ENGINEERING (MANUFACTURING)",
  "ARTIFICIAL INTELLIGENCE AND DATA SCIENCE",
  "COMPUTER SCIENCE AND BUSSINESS SYSTEM",
  "FOOD TECHNOLOGY",
  "BIO TECHNOLOGY",
  "Computer Science and Engineering (Cyber Security)",
  "Artificial Intelligence and Machine Learning",
  "COMPUTER SCIENCE AND DESIGN",
  "Electronics and Communication ( Advanced Communication Technology)",
  "Electronics Engineering (VLSI design and Technology)",
  "BIO MEDICAL ENGINEERING",
  "COMPUTER AND COMMUNICATION ENGINEERING",
  "MEDICAL ELECTRONICS ENGINEERING",
  "MECHANICAL AND AUTOMATION ENGINEERING",
  "PHARMACEUTICAL TECHNOLOGY",
  "AGRICULTURAL ENGINEERING",
  "ROBOTICS AND AUTOMATION",
  "Mechatronics Engineering",
  "PETROLEUM ENGINEERING",
  "Computer Science and Engineering (Internet of Things)",
  "MARINE ENGINEERING",
  "AEROSPACE ENGINEERING",
  "FASHION TECHNOLOGY",
  "M.Tech. Computer Science and Engineering (Integrated 5 years)",
  "PLASTIC TECHNOLOGY",
  "INSTRUMENTATION AND CONTROL ENGINEERING",
  "Cyber Security",
  "AUTOMOBILE ENGINEERING (SS)",
  "BIO TECHNOLOGY (SS)",
  "Computer Science and Engineering (Artificial Intelligence and Machine Learning) (SS)",
  "CIVIL  ENGINEERING (SS)",
  "ELECTRICAL AND ELECTRONICS (SANDWICH) (SS)",
  "FASHION TECHNOLOGY (SS)",
  "INSTRUMENTATION AND CONTROL ENGINEERING (SS)",
  "MECHANICAL ENGINEERING (SS)",
  "MECHANICAL ENGINEERING (SANDWICH) (SS)",
  "METALLURGICAL ENGINEERING",
  "METALLURGICAL ENGINEERING (SS)",
  "PRODUCTION ENGINEERING (SS)",
  "PRODUCTION ENGINEERING (SANDWICH) (SS)",
  "TEXTILE TECHNOLOGY (SS)",
  "ELECTRICAL AND ELECTRONICS ENGINEERING (SS)",
  "COMPUTER SCIENCE AND ENGINEERING (TAMIL)",
  "HANDLOOM AND TEXTILE TECHNOLOGY",
  "Safety and Fire Engineering",
  "PETRO CHEMICAL TECHNOLOGY",
  "TEXTILE CHEMISTRY",
  "Computer Science and Technology",
  "COMPUTER TECHNOLOGY",
  "Information Science and Engineering",
  "ELECTRONICS AND TELECOMMUNICATION ENGINEERING",
  "Mechanical and Mechatronics Engineering (Additive Manufacturing)",
  "Computer Science and Engineering (Internet of Things and Cyber Security including Block Chain Technology)",
  "ENVIRONMENTAL ENGINEERING",
  "Bio Technology and Bio Chemical Engineering",
  "MECHATRONICS",
  "INDUSTRIAL ENGINEERING AND MANAGEMENT",
  "Computer Science and Business System (SS)",
  "MECHATRONICS (SS)",
  "CHEMICAL AND ELECTRO CHEMICAL  ENGINEERING (SS)",
].sort();