export const collegeCourseGroups = {
  "COMPUTER SCIENCE AND ENGINEERING": [
    {
      "S NO": 1,
      "Branch Code": "CS",
      "Branch Name": "COMPUTER SCIENCE AND ENGINEERING",
      Cateogry: 1,
    },
    {
      "S NO": 2,
      "Branch Code": "IT",
      "Branch Name": "INFORMATION TECHNOLOGY",
      Cateogry: 1,
    },
    {
      "S NO": 3,
      "Branch Code": "AD",
      "Branch Name": "ARTIFICIAL INTELLIGENCE AND DATA SCIENCE",
      Cateogry: 1,
    },
    {
      "S NO": 4,
      "Branch Code": "IM",
      "Branch Name": "INFORMATION TECHNOLOGY (SS)",
      Cateogry: 1,
    },
    {
      "S NO": 5,
      "Branch Code": "CM",
      "Branch Name": "COMPUTER SCIENCE AND ENGINEERING\n(SS)",
      Cateogry: 1,
    },
    {
      "S NO": 6,
      "Branch Code": "CB",
      "Branch Name": "COMPUTER SCIENCE AND BUSSINESS\nSYSTEM",
      Cateogry: 1,
    },
    {
      "S NO": 7,
      "Branch Code": "AM",
      "Branch Name":
        "COMPUTER SCIENCE AND ENGINEERING (AI\nAND MACHINE LEARNING)",
      Cateogry: 1,
    },
    {
      "S NO": 8,
      "Branch Code": "AL",
      "Branch Name": "ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING",
      Cateogry: 1,
    },
    {
      "S NO": 9,
      "Branch Code": "SC",
      "Branch Name": "COMPUTER SCIENCE AND ENGINEERING (CYBER SECURITY)",
      Cateogry: 1,
    },
    {
      "S NO": 10,
      "Branch Code": "CD",
      "Branch Name": "COMPUTER SCIENCE AND DESIGN",
      Cateogry: 1,
    },
    {
      "S NO": 11,
      "Branch Code": "AT",
      "Branch Name": "ARTIFICIAL INTELLIGENCE AND DATA\nSCIENCE (SS)",
      Cateogry: 1,
    },
    {
      "S NO": 12,
      "Branch Code": "CJ",
      "Branch Name":
        "M.TECH. COMPUTER SCIENCE AND ENGINEERING (INTEGRATED 5 YEARS)",
      Cateogry: 1,
    },
    {
      "S NO": 13,
      "Branch Code": "CI",
      "Branch Name": "COMPUTER SCIENCE & ENGINEERING (INTERENT OF THINGS)",
      Cateogry: 1,
    },
    {
      "S NO": 14,
      "Branch Code": "CO",
      "Branch Name": "COMPUTER AND COMMUNICATION ENGINEERING",
      Cateogry: 1,
    },
    {
      "S NO": 15,
      "Branch Code": "CG",
      "Branch Name":
        "COMPUTER SCIENCE & ENGINEERING (ARTIFICIAL INTELLIGENCE & MACHINE LEARNING (SS))",
      Cateogry: 1,
    },
    {
      "S NO": 16,
      "Branch Code": "CW",
      "Branch Name": "COMPUTER SCIENCE AND BUSINESS SYSTEM (SS)",
      Cateogry: 1,
    },
    {
      "S NO": 17,
      "Branch Code": "CT",
      "Branch Name": "COMPUTER TECHNOLOGY",
      Cateogry: 1,
    },
    {
      "S NO": 18,
      "Branch Code": "SE",
      "Branch Name": "INFORMATION SCIENCE AND ENGINEERING",
      Cateogry: 1,
    },
    {
      "S NO": 19,
      "Branch Code": "CF",
      "Branch Name": "COMPUTER SCIENCE AND ENGINEERING\n(DATA SCIENCE)",
      Cateogry: 1,
    },
    {
      "S NO": 20,
      "Branch Code": "CY",
      "Branch Name": "CYBER SECURITY",
      Cateogry: 1,
    },
    {
      "S NO": 21,
      "Branch Code": "TS",
      "Branch Name": "COMPUTER SCIENCE AND TECHNOLOGY",
      Cateogry: 1,
    },
    {
      "S NO": 22,
      "Branch Code": "SB",
      "Branch Name":
        "COMPUTER SCIENCE AND ENGINEERING (INTERNET OF THINGS AND CYBER SECURITY INCLUDING BLOCK CHAIN TECHNOLOGY)",
      Cateogry: 1,
    },
    {
      "S NO": 23,
      "Branch Code": "XS",
      "Branch Name": "COMPUTER SCIENCE AND ENGINEERING\n(TAMIL)",
      Cateogry: 1,
    },
  ],
  "ELECTRONICS ENGINEERING": [
    {
      "S NO": 1,
      "Branch Code": "EC",
      "Branch Name": "ELECTRONICS AND COMMUNICATION ENGINEERING",
      Cateogry: 2,
    },
    {
      "S NO": 2,
      "Branch Code": "EE",
      "Branch Name": "ELECTRICAL AND ELECTRONICS ENGINEERING",
      Cateogry: 2,
    },
    {
      "S NO": 3,
      "Branch Code": "EM",
      "Branch Name": "ELECTRONICS AND COMMUNICATION ENGINEERING (SS)",
      Cateogry: 2,
    },
    {
      "S NO": 4,
      "Branch Code": "EI",
      "Branch Name": "ELECTRONICS AND INSTRUMENTATION ENGINEERING",
      Cateogry: 2,
    },
    {
      "S NO": 5,
      "Branch Code": "EY",
      "Branch Name": "ELECTRICAL AND ELECTRONICS ENGINEERING (SS)",
      Cateogry: 2,
    },
    {
      "S NO": 6,
      "Branch Code": "EV",
      "Branch Name":
        "ELECTRONICS & COMMUNICATION ENGINEERING (VLSI DESIGN AND TECHNOLOGY)",
      Cateogry: 2,
    },
    {
      "S NO": 7,
      "Branch Code": "EA",
      "Branch Name":
        "ELECTRONICS &\nCOMMUNICATION ENGINEERING (ADVANCED COMMUNICATION\nTECHNOLOGY)",
      Cateogry: 2,
    },
    {
      "S NO": 8,
      "Branch Code": "IY",
      "Branch Name": "INSTRUMENTATION AND CONTROL\nENGINEERING (SS)",
      Cateogry: 2,
    },
    {
      "S NO": 9,
      "Branch Code": "ES",
      "Branch Name": "ELECTRICAL AND ELECTRONICS (SANDWICH) (SS)",
      Cateogry: 2,
    },
    {
      "S NO": 10,
      "Branch Code": "ET",
      "Branch Name": "ELECTRONICS AND TELECOMMUNICATION ENGINEERING",
      Cateogry: 2,
    },
    {
      "S NO": 11,
      "Branch Code": "MD",
      "Branch Name": "MEDICAL ELECTRONICS ENGINEERING",
      Cateogry: 2,
    },
    {
      "S NO": 12,
      "Branch Code": "IC",
      "Branch Name": "INSTRUMENTATION AND CONTROL\nENGINEERING",
      Cateogry: 2,
    },
  ],
  "MECHANICAL ENGINEERING": [
    {
      "S NO": 1,
      "Branch Code": "ME",
      "Branch Name": "MECHANICAL ENGINEERING",
      Cateogry: 3,
    },
    {
      "S NO": 2,
      "Branch Code": "AE",
      "Branch Name": "AERONAUTICAL ENGINEERING",
      Cateogry: 3,
    },
    {
      "S NO": 3,
      "Branch Code": "MZ",
      "Branch Name": "MECHATRONICS ENGINEERING",
      Cateogry: 3,
    },
    {
      "S NO": 4,
      "Branch Code": "PR",
      "Branch Name": "PRODUCTION ENGINEERING",
      Cateogry: 3,
    },
    {
      "S NO": 5,
      "Branch Code": "MF",
      "Branch Name": "MECHANICAL ENGINEERING (SS)",
      Cateogry: 3,
    },
    {
      "S NO": 6,
      "Branch Code": "AU",
      "Branch Name": "AUTOMOBILE ENGINEERING",
      Cateogry: 3,
    },
    {
      "S NO": 7,
      "Branch Code": "RA",
      "Branch Name": "ROBOTICS AND AUTOMATION (SS)",
      Cateogry: 3,
    },
    {
      "S NO": 8,
      "Branch Code": "MN",
      "Branch Name": "MANUFACTURING ENGINEERING",
      Cateogry: 3,
    },
    {
      "S NO": 9,
      "Branch Code": "PT",
      "Branch Name": "PRINTING TECHNOLOGY",
      Cateogry: 3,
    },
    {
      "S NO": 10,
      "Branch Code": "IE",
      "Branch Name": "INDUSTRIAL ENGINEERING",
      Cateogry: 3,
    },
    {
      "S NO": 11,
      "Branch Code": "RP",
      "Branch Name": "RUBBER AND PLASTIC TECHNOLOGY",
      Cateogry: 3,
    },
    {
      "S NO": 12,
      "Branch Code": "MG",
      "Branch Name": "MECHATRONICS (SS)",
      Cateogry: 3,
    },
    {
      "S NO": 13,
      "Branch Code": "MS",
      "Branch Name": "MECHANICAL ENGINEERING (SANDWICH)\n(SS)",
      Cateogry: 3,
    },
    {
      "S NO": 14,
      "Branch Code": "RM",
      "Branch Name": "ROBOTICS AND AUTOMATION",
      Cateogry: 3,
    },
    {
      "S NO": 15,
      "Branch Code": "AS",
      "Branch Name": "AUTOMOBILE ENGINEERING (SS)",
      Cateogry: 3,
    },
    {
      "S NO": 16,
      "Branch Code": "XM",
      "Branch Name": "MECHANICAL ENGINEERING (TAMIL\nMEDIUM)",
      Cateogry: 3,
    },
    {
      "S NO": 17,
      "Branch Code": "MA",
      "Branch Name": "MATERIAL SCIENCE AND ENGINEERING (SS)",
      Cateogry: 3,
    },
    {
      "S NO": 18,
      "Branch Code": "MT",
      "Branch Name": "METALLURGICAL ENGINEERING",
      Cateogry: 3,
    },
    {
      "S NO": 19,
      "Branch Code": "MI",
      "Branch Name": "MINING ENGINEERING",
      Cateogry: 3,
    },
    {
      "S NO": 20,
      "Branch Code": "AO",
      "Branch Name": "AEROSPACE ENGINEERING",
      Cateogry: 3,
    },
    {
      "S NO": 21,
      "Branch Code": "PN",
      "Branch Name": "PRODUCTION ENGINEERING (SS)",
      Cateogry: 3,
    },
    {
      "S NO": 22,
      "Branch Code": "MY",
      "Branch Name": "METALLURGICAL ENGINEERING (SS)",
      Cateogry: 3,
    },
    {
      "S NO": 23,
      "Branch Code": "PA",
      "Branch Name": "PLASTIC TECHNOLOGY",
      Cateogry: 3,
    },
    {
      "S NO": 24,
      "Branch Code": "MU",
      "Branch Name": "MECHANICAL AND AUTOMATION ENGINEERING",
      Cateogry: 3,
    },
    {
      "S NO": 25,
      "Branch Code": "CR",
      "Branch Name": "CERAMIC TECHNOLOGY (SS)",
      Cateogry: 3,
    },
    {
      "S NO": 26,
      "Branch Code": "PS",
      "Branch Name": "PRODUCTION ENGINEERING (SANDWICH)\n(SS)",
      Cateogry: 3,
    },
    {
      "S NO": 27,
      "Branch Code": "IN",
      "Branch Name": "INDUSTRIAL ENGINEERING AND\nMANAGEMENT",
      Cateogry: 3,
    },
    {
      "S NO": 28,
      "Branch Code": "MM",
      "Branch Name": "MECHANICAL ENGINEERING (MANUFACTURING)",
      Cateogry: 3,
    },
    {
      "S NO": 29,
      "Branch Code": "SF",
      "Branch Name": "SAFETY AND FIRE ENGINEERING",
      Cateogry: 3,
    },
    {
      "S NO": 30,
      "Branch Code": "MC",
      "Branch Name": "MECHATRONICS",
      Cateogry: 3,
    },
    {
      "S NO": 31,
      "Branch Code": "MO",
      "Branch Name":
        "MECHANICAL AND MECHATRONICS ENGINEERING (ADDITIVE MANUFACTURING)",
      Cateogry: 3,
    },
    {
      "S NO": 33,
      "Branch Code": "MR",
      "Branch Name": "MARINE ENGINEERING",
      Cateogry: 3,
    },
    {
      "S NO": 34,
      "Branch Code": "AG",
      "Branch Name": "AGRICULTURE ENGINEERING",
      Cateogry: 3,
    },
  ],
  "CIVIL ENGINEERING": [
    {
      "S NO": 1,
      "Branch Code": "CE",
      "Branch Name": "CIVIL  ENGINEERING",
      Cateogry: 4,
    },
    {
      "S NO": 2,
      "Branch Code": "CN",
      "Branch Name": "CIVIL  ENGINEERING (SS)",
      Cateogry: 4,
    },
    {
      "S NO": 3,
      "Branch Code": "XC",
      "Branch Name": "CIVIL ENGINEERING (TAMIL MEDIUM)",
      Cateogry: 4,
    },
    {
      "S NO": 4,
      "Branch Code": "CZ",
      "Branch Name": "CIVIL AND STRUCTUTURAL ENGINEERING",
      Cateogry: 4,
    },
  ],

  "BIO MEDICAL ENGINEERING": [
    {
      "S NO": 1,
      "Branch Code": "BM",
      "Branch Name": "BIO MEDICAL ENGINEERING",
      Cateogry: 5,
    },
    {
      "S NO": 2,
      "Branch Code": "CH",
      "Branch Name": "CHEMICAL  ENGINEERING",
      Cateogry: 5,
    },
    {
      "S NO": 3,
      "Branch Code": "BT",
      "Branch Name": "BIO TECHNOLOGY",
      Cateogry: 5,
    },
    {
      "S NO": 4,
      "Branch Code": "IB",
      "Branch Name": "INDUSTRIAL BIO TECHNOLOGY",
      Cateogry: 5,
    },
    {
      "S NO": 5,
      "Branch Code": "BY",
      "Branch Name": "BIO MEDICAL ENGINEERING (SS)",
      Cateogry: 5,
    },
    {
      "S NO": 6,
      "Branch Code": "CL",
      "Branch Name": "CHEMICAL  ENGINEERING (SS)",
      Cateogry: 5,
    },
    {
      "S NO": 7,
      "Branch Code": "BS",
      "Branch Name": "BIO TECHNOLOGY (SS)",
      Cateogry: 5,
    },
    {
      "S NO": 8,
      "Branch Code": "FS",
      "Branch Name": "FOOD TECHNOLOGY (SS)",
      Cateogry: 5,
    },
    {
      "S NO": 9,
      "Branch Code": "PP",
      "Branch Name": "PETROLEUM ENGINEERING AND TECHNOLOGY (SS)",
      Cateogry: 5,
    },
    {
      "S NO": 10,
      "Branch Code": "PE",
      "Branch Name": "PETROLEUM ENGINEERING",
      Cateogry: 5,
    },
    {
      "S NO": 11,
      "Branch Code": "CC",
      "Branch Name": "CHEMICAL AND ELECTRO CHEMICAL ENGINEERING (SS)",
      Cateogry: 5,
    },
    {
      "S NO": 12,
      "Branch Code": "FD",
      "Branch Name": "FOOD TECHNOLOGY",
      Cateogry: 5,
    },
    {
      "S NO": 13,
      "Branch Code": "IS",
      "Branch Name": "INDUSTRIAL BIO TECHNOLOGY (SS)",
      Cateogry: 5,
    },
    {
      "S NO": 14,
      "Branch Code": "PC",
      "Branch Name": "PETRO CHEMICAL TECHNOLOGY",
      Cateogry: 5,
    },
    {
      "S NO": 15,
      "Branch Code": "BC",
      "Branch Name": "BIO TECHNOLOGY AND BIO CHEMICAL ENGINEERING",
      Cateogry: 5,
    },
    {
      "S NO": 16,
      "Branch Code": "PM",
      "Branch Name": "PHARMACEUTICAL TECHNOLOGY (SS)",
      Cateogry: 5,
    },
    {
      "S NO": 17,
      "Branch Code": "PH",
      "Branch Name": "PHARMACEUTICAL TECHNOLOGY",
      Cateogry: 5,
    },
  ],
  "TEXTILE TECHNOLOGY": [
    {
      "S NO": 1,
      "Branch Code": "TX",
      "Branch Name": "TEXTILE TECHNOLOGY",
      Cateogry: 6,
    },
    {
      "S NO": 2,
      "Branch Code": "FY",
      "Branch Name": "FASHION TECHNOLOGY (SS)",
      Cateogry: 6,
    },
    {
      "S NO": 3,
      "Branch Code": "FT",
      "Branch Name": "FASHION TECHNOLOGY",
      Cateogry: 6,
    },
    {
      "S NO": 4,
      "Branch Code": "TT",
      "Branch Name": "TEXTILE TECHNOLOGY (SS)",
      Cateogry: 6,
    },
    {
      "S NO": 5,
      "Branch Code": "TC",
      "Branch Name": "TEXTILE CHEMISTRY",
      Cateogry: 6,
    },
    {
      "S NO": 6,
      "Branch Code": "HT",
      "Branch Name": "HANDLOOM AND TEXTILE TECHNOLOGY",
      Cateogry: 6,
    },
  ],
  "OTHERS": [
    {
      "S NO": 1,
      "Branch Code": "GI",
      "Branch Name": "GEO INFORMATICS",
      Cateogry: 7,
    },
    {
      "S NO": 2,
      "Branch Code": "LE",
      "Branch Name": "LEATHER TECHNOLOGY",
      Cateogry: 7,
    },
    {
      "S NO": 3,
      "Branch Code": "AP",
      "Branch Name": "APPAREL TECHNOLOGY (SS)",
      Cateogry: 7,
    },
    {
      "S NO": 4,
      "Branch Code": "EN",
      "Branch Name": "ENVIRONMENTAL ENGINEERING",
      Cateogry: 7,
    },
  ],
};
