export const medicalCutoffData = [
  {
    "College Name": "MADRAS MEDICAL COLLEGE, CHENNAI",
    "College Type": "Govt",
    "Quota": "GQ",
    "OC - State Rank": 146,
    "OC - NEET Mark": 671,
    "BC - State Rank": 234,
    "BC - NEET Mark": 663,
    "BCM - State Rank": 350,
    "BCM - NEET Mark": 651,
    "MBC & DNC - State Rank- State Rank": 345,
    "MBC & DNC - NEET Mark": 651,
    "SC - State Rank": 1300,
    "SC - NEET Mark": 607,
    "SCA - State Rank": 1650,
    "SCA - NEET Mark": 596,
    "ST - State Rank": 6451,
    "ST - NEET Mark": 499,
  },
  {
    "College Name": "STANLEY MEDICAL COLLEGE, CHENNAI",
    "College Type": "Govt",
    "Quota": "GQ",
    "OC - State Rank": 313,
    "OC - NEET Mark": 654,
    "BC - State Rank": 1954,
    "BC - NEET Mark": 587,
    "BCM - State Rank": 478,
    "BCM - NEET Mark": 642,
    "MBC & DNC - State Rank": 606,
    "MBC & DNC - NEET Mark": 635,
    "SC - State Rank": 8796,
    "SC - NEET Mark": 460,
    "SCA - State Rank": 3623,
    "SCA - NEET Mark": 550,
    "ST - State Rank": 6695,
    "ST - NEET Mark": 495,
  },
  {
    "College Name": "COIMBATORE MEDICAL COLLEGE, COIMBATORE",
    "College Type": "Govt",
    "Quota": "GQ",
    "OC - State Rank": 454,
    "OC - NEET Mark": 644,
    "BC - State Rank": 941,
    "BC - NEET Mark": 621,
    "BCM - State Rank": 1636,
    "BCM - NEET Mark": 596,
    "MBC & DNC - State Rank": 1193,
    "MBC & DNC - NEET Mark": 611,
    "SC - State Rank": 4748,
    "SC - NEET Mark": 529,
    "SCA - State Rank": 6661,
    "SCA - NEET Mark": 496,
    "ST - State Rank": 7561,
    "ST - NEET Mark": 481,
  },
  {
    "College Name": "KILPAUK MEDICAL COLLEGE, CHENNAI",
    "College Type": "Govt",
    "Quota": "GQ",
    "OC - State Rank": 506,
    "OC - NEET Mark": 641,
    "BC - State Rank": 695,
    "BC - NEET Mark": 631,
    "BCM - State Rank": 662,
    "BCM - NEET Mark": 633,
    "MBC & DNC - State Rank": 811,
    "MBC & DNC - NEET Mark": 626,
    "SC - State Rank": 9154,
    "SC - NEET Mark": 454,
    "SCA - State Rank": 5305,
    "SCA - NEET Mark": 519,
    "ST - State Rank": 7211,
    "ST - NEET Mark": 487,
  },
  {
    "College Name": "MADURAI MEDICAL COLLEGE, MADURAI",
    "College Type": "Govt",
    "Quota": "GQ",
    "OC - State Rank": 607,
    "OC - NEET Mark": 635,
    "BC - State Rank": 930,
    "BC - NEET Mark": 621,
    "BCM - State Rank": 1077,
    "BCM - NEET Mark": 615,
    "MBC & DNC - State Rank": 1358,
    "MBC & DNC - NEET Mark": 605,
    "SC - State Rank": 5223,
    "SC - NEET Mark": 521,
    "SCA - State Rank": 7436,
    "SCA - NEET Mark": 483,
    "ST - State Rank": 8418,
    "ST - NEET Mark": 466,
  },
  {
    "College Name": "GOVERNMENT MEDICAL COLLEGE, OMANDURAR,CHENNAI",
    "College Type": "Govt",
    "Quota": "GQ",
    "OC - State Rank": 704,
    "OC - NEET Mark": 631,
    "BC - State Rank": 850,
    "BC - NEET Mark": 625,
    "BCM - State Rank": 884,
    "BCM - NEET Mark": 623,
    "MBC & DNC - State Rank": 1063,
    "MBC & DNC - NEET Mark": 615,
    "SC - State Rank": 3920,
    "SC - NEET Mark": 544,
    "SCA - State Rank": 6692,
    "SCA - NEET Mark": 496,
    "ST - State Rank": 9637,
    "ST - NEET Mark": 444,
  },
  {
    "College Name": "CHENGALPATTU MEDICAL COLLEGE, CHENGALPATTU",
    "College Type": "Govt",
    "Quota": "GQ",
    "OC - State Rank": 879,
    "OC - NEET Mark": 623,
    "BC - State Rank": 1208,
    "BC - NEET Mark": 610,
    "BCM - State Rank": 1270,
    "BCM - NEET Mark": 608,
    "MBC & DNC - State Rank": 1453,
    "MBC & DNC - NEET Mark": 602,
    "SC - State Rank": 5333,
    "SC - NEET Mark": 518,
    "SCA - State Rank": 8371,
    "SCA - NEET Mark": 467,
    "ST - State Rank": 10314,
    "ST - NEET Mark": 432,
  },
  {
    "College Name": "GOVERNMENT MEDICAL COLLEGE & ESIC HOSPITAL, COIMBATORE",
    "College Type": "Govt",
    "Quota": "GQ",
    "OC - State Rank": 912,
    "OC - NEET Mark": 622,
    "BC - State Rank": 1439,
    "BC - NEET Mark": 602,
    "BCM - State Rank": 1911,
    "BCM - NEET Mark": 589,
    "MBC & DNC - State Rank": 1720,
    "MBC & DNC - NEET Mark": 594,
    "SC - State Rank": 5915,
    "SC - NEET Mark": 508,
    "SCA - State Rank": 9081,
    "SCA - NEET Mark": 455,
    "ST - State Rank": 10241,
    "ST - NEET Mark": 433,
  },
  {
    "College Name": "THANJAVUR MEDICAL COLLEGE,THANJAVUR",
    "College Type": "Govt",
    "Quota": "GQ",
    "OC - State Rank": 927,
    "OC - NEET Mark": 621,
    "BC - State Rank": 1213,
    "BC - NEET Mark": 610,
    "BCM - State Rank": 1914,
    "BCM - NEET Mark": 588,
    "MBC & DNC - State Rank": 1544,
    "MBC & DNC - NEET Mark": 599,
    "SC - State Rank": 5741,
    "SC - NEET Mark": 511,
    "SCA - State Rank": 8578,
    "SCA - NEET Mark": 463,
    "ST - State Rank": 8558,
    "ST - NEET Mark": 464,
  },
  {
    "College Name": "MOHAN KUMARAMANGALAM MEDICAL COLLEGE, SALEM",
    "College Type": "Govt",
    "Quota": "GQ",
    "OC - State Rank": 1040,
    "OC - NEET Mark": 617,
    "BC - State Rank": 1339,
    "BC - NEET Mark": 605,
    "BCM - State Rank": 1687,
    "BCM - NEET Mark": 595,
    "MBC & DNC - State Rank": 1627,
    "MBC & DNC - NEET Mark": 597,
    "SC - State Rank": 5474,
    "SC - NEET Mark": 516,
    "SCA - State Rank": 8642,
    "SCA - NEET Mark": 462,
    "ST - State Rank": 9898,
    "ST - NEET Mark": 439,
  },
  {
    "College Name": "ESI-PGIMSR,ESI HOSPITAL,K.K NAGAR,CHENNAI",
    "College Type": "Govt",
    "Quota": "GQ",
    "OC - State Rank": 1059,
    "OC - NEET Mark": 616,
    "BC - State Rank": 1612,
    "BC - NEET Mark": 597,
    "BCM - State Rank": 1392,
    "BCM - NEET Mark": 604,
    "MBC & DNC - State Rank": 2218,
    "MBC & DNC - NEET Mark": 580,
    "SC - State Rank": 7069,
    "SC - NEET Mark": 490,
    "SCA - State Rank": 10839,
    "SCA - NEET Mark": 422,
    "ST - State Rank": 9717,
    "ST - NEET Mark": 442,
  },
  {
    "College Name": "GOVT. TIRUPPUR MEDICAL COLLEGE HOSPITAL, TIRUPPUR.",
    "College Type": "Govt",
    "Quota": "GQ",
    "OC - State Rank": 1188,
    "OC - NEET Mark": 611,
    "BC - State Rank": 2213,
    "BC - NEET Mark": 580,
    "BCM - State Rank": 3290,
    "BCM - NEET Mark": 556,
    "MBC & DNC - State Rank": 3349,
    "MBC & DNC - NEET Mark": 555,
    "SC - State Rank": 8225,
    "SC - NEET Mark": 469,
    "SCA - State Rank": 11030,
    "SCA - NEET Mark": 418,
    "ST - State Rank": 11574,
    "ST - NEET Mark": 408,
  },
  {
    "College Name": "GOVERNMENT DHARMAPURI MEDICAL COLLEGE, DHARMAPURI",
    "College Type": "Govt",
    "Quota": "GQ",
    "OC - State Rank": 1230,
    "OC - NEET Mark": 610,
    "BC - State Rank": 2113,
    "BC - NEET Mark": 583,
    "BCM - State Rank": 2755,
    "BCM - NEET Mark": 567,
    "MBC & DNC - State Rank": 2355,
    "MBC & DNC - NEET Mark": 577,
    "SC - State Rank": 7760,
    "SC - NEET Mark": 478,
    "SCA - State Rank": 10179,
    "SCA - NEET Mark": 434,
    "ST - State Rank": 11094,
    "ST - NEET Mark": 417,
  },
  {
    "College Name": "GOVERNMENT ERODE MEDICAL COLLEGE & HOSPITAL, PERUNDURAI",
    "College Type": "Govt",
    "Quota": "GQ",
    "OC - State Rank": 1246,
    "OC - NEET Mark": 610,
    "BC - State Rank": 1997,
    "BC - NEET Mark": 586,
    "BCM - State Rank": 2451,
    "BCM - NEET Mark": 574,
    "MBC & DNC - State Rank": 2557,
    "MBC & DNC - NEET Mark": 572,
    "SC - State Rank": 6424,
    "SC - NEET Mark": 500,
    "SCA - State Rank": 10458,
    "SCA - NEET Mark": 429,
    "ST - State Rank": 10380,
    "ST - NEET Mark": 431,
  },
  {
    "College Name": "K A P VISWANATHAN GOVERNMENT MEDICAL COLLEGE, TRICHY",
    "College Type": "Govt",
    "Quota": "GQ",
    "OC - State Rank": 1251,
    "OC - NEET Mark": 609,
    "BC - State Rank": 1491,
    "BC - NEET Mark": 600,
    "BCM - State Rank": 1867,
    "BCM - NEET Mark": 590,
    "MBC & DNC - State Rank": 1829,
    "MBC & DNC - NEET Mark": 591,
    "SC - State Rank": 6071,
    "SC - NEET Mark": 506,
    "SCA - State Rank": 9631,
    "SCA - NEET Mark": 444,
    "ST - State Rank": 10051,
    "ST - NEET Mark": 436,
  },
  {
    "College Name": "THENI GOVERNMENT MEDICAL COLLEGE,THENI",
    "College Type": "Govt",
    "Quota": "GQ",
    "OC - State Rank": 1251,
    "OC - NEET Mark": 609,
    "BC - State Rank": 1782,
    "BC - NEET Mark": 592,
    "BCM - State Rank": 2524,
    "BCM - NEET Mark": 572,
    "MBC & DNC - State Rank": 2582,
    "MBC & DNC - NEET Mark": 571,
    "SC - State Rank": 7462,
    "SC - NEET Mark": 483,
    "SCA - State Rank": 9708,
    "SCA - NEET Mark": 443,
    "ST - State Rank": 11356,
    "ST - NEET Mark": 413,
  },
  {
    "College Name": "TIRUNELVELI MEDICAL COLLEGE,TIRUNELVELI",
    "College Type": "Govt",
    "Quota": "GQ",
    "OC - State Rank": 1297,
    "OC - NEET Mark": 607,
    "BC - State Rank": 1614,
    "BC - NEET Mark": 597,
    "BCM - State Rank": 1800,
    "BCM - NEET Mark": 592,
    "MBC & DNC - State Rank": 2104,
    "MBC & DNC - NEET Mark": 583,
    "SC - State Rank": 6535,
    "SC - NEET Mark": 498,
    "SCA - State Rank": 9924,
    "SCA - NEET Mark": 439,
    "ST - State Rank": 9026,
    "ST - NEET Mark": 456,
  },
  {
    "College Name": "GOVERNMENT VILLUPURAM MEDICAL COLLEGE, VILLUPURAM",
    "College Type": "Govt",
    "Quota": "GQ",
    "OC - State Rank": 1306,
    "OC - NEET Mark": 607,
    "BC - State Rank": 1846,
    "BC - NEET Mark": 591,
    "BCM - State Rank": 2139,
    "BCM - NEET Mark": 582,
    "MBC & DNC - State Rank": 2468,
    "MBC & DNC - NEET Mark": 574,
    "SC - State Rank": 6672,
    "SC - NEET Mark": 496,
    "SCA - State Rank": 10270,
    "SCA - NEET Mark": 433,
    "ST - State Rank": 13200,
    "ST - NEET Mark": 376,
  },
  {
    "College Name": "KANYAKUMARI GOVERNMENT MEDICAL COLLEGE, ASARIPALLAM",
    "College Type": "Govt",
    "Quota": "GQ",
    "OC - State Rank": 1319,
    "OC - NEET Mark": 606,
    "BC - State Rank": 2274,
    "BC - NEET Mark": 579,
    "BCM - State Rank": 2611,
    "BCM - NEET Mark": 570,
    "MBC & DNC - State Rank": 3534,
    "MBC & DNC - NEET Mark": 551,
    "SC - State Rank": 8822,
    "SC - NEET Mark": 459,
    "SCA - State Rank": 11675,
    "SCA - NEET Mark": 406,
    "ST - State Rank": 13072,
    "ST - NEET Mark": 378,
  },
  {
    "College Name": "GOVERNMENT MEDICAL COLLEGE AND HOSPITAL, CUDDALORE",
    "College Type": "Govt",
    "Quota": "GQ",
    "OC - State Rank": 1325,
    "OC - NEET Mark": 606,
    "BC - State Rank": 2903,
    "BC - NEET Mark": 564,
    "BCM - State Rank": 3351,
    "BCM - NEET Mark": 555,
    "MBC & DNC - State Rank": 3501,
    "MBC & DNC - NEET Mark": 552,
    "SC - State Rank": 8468,
    "SC - NEET Mark": 465,
    "SCA - State Rank": 12479,
    "SCA - NEET Mark": 390,
    "ST - State Rank": 11545,
    "ST - NEET Mark": 409,
  },
  {
    "College Name": "GOVT. THIRUVALLUR MEDICAL COLLEGE HOSPITAL,",
    "College Type": "Govt",
    "Quota": "GQ",
    "OC - State Rank": 1402,
    "OC - NEET Mark": 604,
    "BC - State Rank": 2100,
    "BC - NEET Mark": 583,
    "BCM - State Rank": 1796,
    "BCM - NEET Mark": 592,
    "MBC & DNC - State Rank": 2801,
    "MBC & DNC - NEET Mark": 566,
    "SC - State Rank": 7173,
    "SC - NEET Mark": 488,
    "SCA - State Rank": 11300,
    "SCA - NEET Mark": 414,
    "ST - State Rank": 11082,
    "ST - NEET Mark": 417,
  },
  {
    "College Name": "GOVERNMENT VELLORE MEDICAL COLLEGE, VELLORE",
    "College Type": "Govt",
    "Quota": "GQ",
    "OC - State Rank": 1442,
    "OC - NEET Mark": 602,
    "BC - State Rank": 1670,
    "BC - NEET Mark": 596,
    "BCM - State Rank": 2069,
    "BCM - NEET Mark": 584,
    "MBC & DNC - State Rank": 2066,
    "MBC & DNC - NEET Mark": 584,
    "SC - State Rank": 6798,
    "SC - NEET Mark": 494,
    "SCA - State Rank": 7817,
    "SCA - NEET Mark": 477,
    "ST - State Rank": 10526,
    "ST - NEET Mark": 428,
  },
  {
    "College Name": "GOVERNMENT MEDICAL COLLEGE, KARUR",
    "College Type": "Govt",
    "Quota": "GQ",
    "BC - State Rank": 2284,
    "BC - NEET Mark": 579,
    "BCM - State Rank": 3112,
    "BCM - NEET Mark": 560,
    "MBC & DNC - State Rank": 3119,
    "MBC & DNC - NEET Mark": 560,
    "SC - State Rank": 8635,
    "SC - NEET Mark": 462,
    "SCA - State Rank": 10887,
    "SCA - NEET Mark": 421,
    "ST - State Rank": 12481,
    "ST - NEET Mark": 390,
  },
  {
    "College Name": "GOVERNMENT MEDICAL COLLEGE, PUDUKOTTAI",
    "College Type": "Govt",
    "Quota": "GQ",
    "BC - State Rank": 2477,
    "BC - NEET Mark": 574,
    "BCM - State Rank": 2977,
    "BCM - NEET Mark": 563,
    "MBC & DNC - State Rank": 3638,
    "MBC & DNC - NEET Mark": 549,
    "SC - State Rank": 8107,
    "SC - NEET Mark": 471,
    "SCA - State Rank": 12075,
    "SCA - NEET Mark": 398,
    "ST - State Rank": 12947,
    "ST - NEET Mark": 380,
  },
  {
    "College Name": "GOVERNMENT SIVAGANGAI MEDICAL COLLEGE, SIVAGANGA",
    "College Type": "Govt",
    "Quota": "GQ",
    "BC - State Rank": 2990,
    "BC - NEET Mark": 562,
    "BCM - State Rank": 3083,
    "BCM - NEET Mark": 561,
    "MBC & DNC - State Rank": 3944,
    "MBC & DNC - NEET Mark": 543,
    "SC - State Rank": 8705,
    "SC - NEET Mark": 461,
    "SCA - State Rank": 10929,
    "SCA - NEET Mark": 420,
    "ST - State Rank": 13820,
    "ST - NEET Mark": 363,
  },
  {
    "College Name":
      "GOVERNMENT THIRUVANNAMALAI MEDICAL COLLEGE, THIRUVANNAMALAI",
    "College Type": "Govt",
    "Quota": "GQ",
    "BC - State Rank": 2141,
    "BC - NEET Mark": 582,
    "BCM - State Rank": 2857,
    "BCM - NEET Mark": 565,
    "MBC & DNC - State Rank": 2852,
    "MBC & DNC - NEET Mark": 566,
    "SC - State Rank": 7389,
    "SC - NEET Mark": 484,
    "SCA - State Rank": 11568,
    "SCA - NEET Mark": 408,
    "ST - State Rank": 13134,
    "ST - NEET Mark": 377,
  },
  {
    "College Name": "GOVT. DINDIGUL MEDICAL COLLEGE HOSPITAL, DINDIGUL",
    "College Type": "Govt",
    "Quota": "GQ",
    "BC - State Rank": 2868,
    "BC - NEET Mark": 565,
    "BCM - State Rank": 3697,
    "BCM - NEET Mark": 548,
    "MBC & DNC - State Rank": 4301,
    "MBC & DNC - NEET Mark": 537,
    "SC - State Rank": 8994,
    "SC - NEET Mark": 457,
    "SCA - State Rank": 12041,
    "SCA - NEET Mark": 399,
    "ST - State Rank": 13893,
    "ST - NEET Mark": 361,
  },
  {
    "College Name": "GOVT. KRISHNAGIRI MEDICAL COLLEGE HOSPITAL,",
    "College Type": "Govt",
    "Quota": "GQ",
    "BC - State Rank": 2761,
    "BC - NEET Mark": 567,
    "BCM - State Rank": 3667,
    "BCM - NEET Mark": 549,
    "MBC & DNC - State Rank": 3872,
    "MBC & DNC - NEET Mark": 545,
    "SC - State Rank": 8678,
    "SC - NEET Mark": 462,
    "SCA - State Rank": 12275,
    "SCA - NEET Mark": 395,
  },
  {
    "College Name": "GOVT. MEDICAL COLLEGE HOSPITAL, VIRUDHUNAGAR.",
    "College Type": "Govt",
    "Quota": "GQ",
    "BC - State Rank": 3064,
    "BC - NEET Mark": 561,
    "BCM - State Rank": 3159,
    "BCM - NEET Mark": 559,
    "MBC & DNC - State Rank": 4339,
    "MBC & DNC - NEET Mark": 536,
    "SC - State Rank": 9263,
    "SC - NEET Mark": 451,
    "SCA - State Rank": 12468,
    "SCA - NEET Mark": 390,
    "ST - State Rank": 13300,
    "ST - NEET Mark": 374,
  },
  {
    "College Name": "GOVT. NAGAPATTINAM MEDICAL COLLEGE HOSPITAL,",
    "College Type": "Govt",
    "Quota": "GQ",
    "BC - State Rank": 3302,
    "BC - NEET Mark": 556,
    "BCM - State Rank": 4071,
    "BCM - NEET Mark": 541,
    "MBC & DNC - State Rank": 4648,
    "MBC & DNC - NEET Mark": 531,
    "SC - State Rank": 9330,
    "SC - NEET Mark": 450,
    "SCA - State Rank": 12797,
    "SCA - NEET Mark": 383,
    "ST - State Rank": 13582,
    "ST - NEET Mark": 368,
  },
  {
    "College Name": "GOVT. NAMAKKAL MEDICAL COLLEGE HOSPITAL, NAMAKKAL.",
    "College Type": "Govt",
    "Quota": "GQ",
    "BC - State Rank": 2686,
    "BC - NEET Mark": 569,
    "BCM - State Rank": 3773,
    "BCM - NEET Mark": 547,
    "MBC & DNC - State Rank": 3895,
    "MBC & DNC - NEET Mark": 544,
    "SC - State Rank": 8921,
    "SC - NEET Mark": 458,
    "SCA - State Rank": 10249,
    "SCA - NEET Mark": 433,
    "ST - State Rank": 12600,
    "ST - NEET Mark": 387,
  },
  {
    "College Name": "GOVT. RAMANATHAPURAM MEDICAL COLLEGE HOSPITAL,",
    "College Type": "Govt",
    "Quota": "GQ",
    "BC - State Rank": 3160,
    "BC - NEET Mark": 559,
    "BCM - State Rank": 3709,
    "BCM - NEET Mark": 548,
    "MBC & DNC - State Rank": 4589,
    "MBC & DNC - NEET Mark": 532,
    "SC - State Rank": 9392,
    "SC - NEET Mark": 449,
    "SCA - State Rank": 12654,
    "SCA - NEET Mark": 386,
    "ST - State Rank": 14127,
    "ST - NEET Mark": 357,
  },
  {
    "College Name": "GOVT. THE NILGIRIS MEDICAL COLLEGE HOSPITAL, THE NILGIRIS",
    "College Type": "Govt",
    "Quota": "GQ",
    "BC - State Rank": 3288,
    "BC - NEET Mark": 556,
    "BCM - State Rank": 4045,
    "BCM - NEET Mark": 542,
    "MBC & DNC - State Rank": 4717,
    "MBC & DNC - NEET Mark": 530,
    "SC - State Rank": 9431,
    "SC - NEET Mark": 448,
    "SCA - State Rank": 12836,
    "SCA - NEET Mark": 382,
    "ST - State Rank": 14141,
    "ST - NEET Mark": 357,
  },
  {
    "College Name": "GOVT.ARIYALUR MEDICAL COLLEGE HOSPITAL, ARIYALUR.",
    "College Type": "Govt",
    "Quota": "GQ",
    "BC - State Rank": 3073,
    "BC - NEET Mark": 561,
    "BCM - State Rank": 3738,
    "BCM - NEET Mark": 547,
    "MBC & DNC - State Rank": 4255,
    "MBC & DNC - NEET Mark": 538,
    "SC - State Rank": 8969,
    "SC - NEET Mark": 457,
    "SCA - State Rank": 12458,
    "SCA - NEET Mark": 391,
    "ST - State Rank": 13955,
    "ST - NEET Mark": 360,
  },
  {
    "College Name": "GOVT.KALLAKURUCHI MEDICAL COLLEGE HOSPITAL,",
    "College Type": "Govt",
    "Quota": "GQ",
    "BC - State Rank": 3050,
    "BC - NEET Mark": 561,
    "BCM - State Rank": 3941,
    "BCM - NEET Mark": 543,
    "MBC & DNC - State Rank": 4194,
    "MBC & DNC - NEET Mark": 539,
    "SC - State Rank": 8977,
    "SC - NEET Mark": 457,
    "SCA - State Rank": 12580,
    "SCA - NEET Mark": 388,
    "ST - State Rank": 14234,
    "ST - NEET Mark": 355,
  },
  {
    "College Name": "THIRUVARUR GOVT. MEDICAL COLLEGE, THIRUVARUR",
    "College Type": "Govt",
    "Quota": "GQ",
    "BC - State Rank": 2958,
    "BC - NEET Mark": 563,
    "BCM - State Rank": 2986,
    "BCM - NEET Mark": 562,
    "MBC & DNC - State Rank": 3784,
    "MBC & DNC - NEET Mark": 546,
    "SC - State Rank": 8675,
    "SC - NEET Mark": 462,
    "SCA - State Rank": 10873,
    "SCA - NEET Mark": 421,
    "ST - State Rank": 13527,
    "ST - NEET Mark": 369,
  },
  {
    "College Name": "THOOTHUKUDI MEDICAL COLLEGE, THOOTHUKUDI",
    "College Type": "Govt",
    "Quota": "GQ",
    "BC - State Rank": 2445,
    "BC - NEET Mark": 575,
    "BCM - State Rank": 2659,
    "BCM - NEET Mark": 569,
    "MBC & DNC - State Rank": 3447,
    "MBC & DNC - NEET Mark": 553,
    "SC - State Rank": 8639,
    "SC - NEET Mark": 462,
    "SCA - State Rank": 11123,
    "SCA - NEET Mark": 417,
    "ST - State Rank": 12689,
    "ST - NEET Mark": 386,
  },
  {
    "College Name":
      "SRI VENKATESWARAA MEDICAL COLLEGE HOSPITAL AND RESEARCH INSTITUTE, CHENNAI  (PRIVATE UNIVERSITY)",
    "College Type": "PU",
    "Quota": "GQ",
    "OC - State Rank": 6086,
    "OC - NEET Mark": 506,
    "BC - State Rank": 6842,
    "BC - NEET Mark": 493,
    "BCM - State Rank": 7243,
    "BCM - NEET Mark": 487,
    "MBC & DNC - State Rank": 7829,
    "MBC & DNC - NEET Mark": 477,
    "SC - State Rank": 12380,
    "SC - NEET Mark": 392,
    "SCA - State Rank": 16373,
    "SCA - NEET Mark": 315,
    "ST - State Rank": 17134,
    "ST - NEET Mark": 301,
  },
  {
    "College Name":
      "SRINIVASAN MEDICAL COLLEGE & HOSPITAL, SAMAYAPURAM, TRICHY",
    "College Type": "PU",
    "Quota": "GQ",
    "OC - State Rank": 6194,
    "OC - NEET Mark": 504,
    "BC - State Rank": 6604,
    "BC - NEET Mark": 497,
    "BCM - State Rank": 7379,
    "BCM - NEET Mark": 484,
    "MBC & DNC - State Rank": 7713,
    "MBC & DNC - NEET Mark": 478,
    "SC - State Rank": 12218,
    "SC - NEET Mark": 396,
    "SCA - State Rank": 16231,
    "SCA - NEET Mark": 318,
    "ST - State Rank": 17111,
    "ST - NEET Mark": 302,
  },
  {
    "College Name":
      "DHANALAKSHMI SRINIVASAN INSTITUTE OF MEDICAL SCIENCES AND HOSPITAL, PERAMBALUR",
    "College Type": "PU",
    "Quota": "GQ",
    "OC - State Rank": 6334,
    "OC - NEET Mark": 502,
    "BC - State Rank": 6836,
    "BC - NEET Mark": 493,
    "BCM - State Rank": 7570,
    "BCM - NEET Mark": 481,
    "MBC & DNC - State Rank": 7985,
    "MBC & DNC - NEET Mark": 473,
    "SC - State Rank": 12300,
    "SC - NEET Mark": 394,
    "SCA - State Rank": 15831,
    "SCA - NEET Mark": 325,
  },
  {
    "College Name": "CHRISTIAN MEDICAL COLLEGE, VELLORE",
    "College Type": "SF",
    "Quota": "GQ",
    "OC - State Rank": 112,
    "OC - NEET Mark": 677,
    "BC - State Rank": 428,
    "BC - NEET Mark": 645,
    "MBC & DNC - State Rank": 677,
    "MBC & DNC - NEET Mark": 632,
    "SC - State Rank": 2077,
    "SC - NEET Mark": 584,
    "ST - State Rank": 13626,
    "ST - NEET Mark": 367,
  },
  {
    "College Name": "PSG INSTITUTE OF MEDICAL SCIENCES, COIMBATORE",
    "College Type": "SF",
    "Quota": "GQ",
    "OC - State Rank": 2112,
    "OC - NEET Mark": 583,
    "BC - State Rank": 3393,
    "BC - NEET Mark": 554,
    "BCM - State Rank": 4906,
    "BCM - NEET Mark": 526,
    "MBC & DNC - State Rank": 4844,
    "MBC & DNC - NEET Mark": 527,
    "SC - State Rank": 9674,
    "SC - NEET Mark": 443,
    "SCA - State Rank": 13044,
    "SCA - NEET Mark": 379,
    "ST - State Rank": 14359,
    "ST - NEET Mark": 353,
  },
  {
    "College Name":
      "KMCH INSTITUTE OF HEALTH SCIENCES AND RESEARCH, COIMBATORE",
    "College Type": "SF",
    "Quota": "GQ",
    "OC - State Rank": 3108,
    "OC - NEET Mark": 560,
    "BC - State Rank": 3403,
    "BC - NEET Mark": 554,
    "BCM - State Rank": 4485,
    "BCM - NEET Mark": 534,
    "MBC & DNC - State Rank": 5027,
    "MBC & DNC - NEET Mark": 524,
    "SC - State Rank": 9947,
    "SC - NEET Mark": 439,
    "SCA - State Rank": 14214,
    "SCA - NEET Mark": 355,
    "ST - State Rank": 14423,
    "ST - NEET Mark": 351,
  },
  {
    "College Name":
      "VELAMMAL MEDICAL COLLEGE HOSPITAL AND RESEARCH INSTITUTE, MADURAI",
    "College Type": "SF",
    "Quota": "GQ",
    "OC - State Rank": 3455,
    "OC - NEET Mark": 553,
    "BC - State Rank": 3685,
    "BC - NEET Mark": 548,
    "BCM - State Rank": 4889,
    "BCM - NEET Mark": 526,
    "MBC & DNC - State Rank": 5457,
    "MBC & DNC - NEET Mark": 516,
    "SC - State Rank": 10422,
    "SC - NEET Mark": 430,
    "SCA - State Rank": 13981,
    "SCA - NEET Mark": 360,
    "ST - State Rank": 14846,
    "ST - NEET Mark": 344,
  },
  {
    "College Name":
      "PANIMALAR MEDICAL COLLEGE HOSPITAL & RESEARCH INSTITUTE, CHENNAI,TAMIL NADU",
    "College Type": "SF",
    "Quota": "GQ",
    "OC - State Rank": 3557,
    "OC - NEET Mark": 551,
    "BC - State Rank": 4211,
    "BC - NEET Mark": 539,
    "BCM - State Rank": 4694,
    "BCM - NEET Mark": 530,
    "MBC & DNC - State Rank": 6122,
    "MBC & DNC - NEET Mark": 505,
    "SC - State Rank": 10759,
    "SC - NEET Mark": 423,
    "SCA - State Rank": 14780,
    "SCA - NEET Mark": 345,
    "ST - State Rank": 16439,
    "ST - NEET Mark": 314,
  },
  {
    "College Name":
      "TRICHY SRM MEDICAL COLLEGE HOSPITAL & RESEARCH CENTRE, TRICHY",
    "College Type": "SF",
    "Quota": "GQ",
    "OC - State Rank": 3597,
    "OC - NEET Mark": 550,
    "BC - State Rank": 3824,
    "BC - NEET Mark": 546,
    "BCM - State Rank": 4522,
    "BCM - NEET Mark": 533,
    "MBC & DNC - State Rank": 6238,
    "MBC & DNC - NEET Mark": 503,
    "SC - State Rank": 10768,
    "SC - NEET Mark": 423,
    "SCA - State Rank": 13794,
    "SCA - NEET Mark": 363,
  },
  {
    "College Name":
      "KARPAGA VINAYAGA INSTITUTE OF MEDICAL SCIENCES,MADURANTHAGAM",
    "College Type": "SF",
    "Quota": "GQ",
    "OC - State Rank": 3645,
    "OC - NEET Mark": 549,
    "BC - State Rank": 4240,
    "BC - NEET Mark": 538,
    "BCM - State Rank": 4624,
    "BCM - NEET Mark": 531,
    "MBC & DNC - State Rank": 5539,
    "MBC & DNC - NEET Mark": 515,
    "SC - State Rank": 10497,
    "SC - NEET Mark": 428,
    "SCA - State Rank": 14980,
    "SCA - NEET Mark": 341,
    "ST - State Rank": 14531,
    "ST - NEET Mark": 349,
  },
  {
    "College Name":
      "KARPAGAM FACULTY OF MEDICAL SCIENCES & RESEARCH, COIMBATORE",
    "College Type": "SF",
    "Quota": "GQ",
    "OC - State Rank": 3855,
    "OC - NEET Mark": 545,
    "BC - State Rank": 4405,
    "BC - NEET Mark": 535,
    "BCM - State Rank": 5151,
    "BCM - NEET Mark": 522,
    "MBC & DNC - State Rank": 7221,
    "MBC & DNC - NEET Mark": 487,
    "SC - State Rank": 10605,
    "SC - NEET Mark": 426,
    "SCA - State Rank": 13760,
    "SCA - NEET Mark": 364,
  },
  {
    "College Name":
      "MELMARUVATHUR ADHIPARASAKTHI INSTITUTE OF MEDICAL SCIENCES AND RESEARCH,MELMARUVATHUR",
    "College Type": "SF",
    "Quota": "GQ",
    "OC - State Rank": 3907,
    "OC - NEET Mark": 544,
    "BC - State Rank": 4358,
    "BC - NEET Mark": 536,
    "BCM - State Rank": 5445,
    "BCM - NEET Mark": 516,
    "MBC & DNC - State Rank": 5718,
    "MBC & DNC - NEET Mark": 512,
    "SC - State Rank": 10818,
    "SC - NEET Mark": 422,
    "SCA - State Rank": 14700,
    "SCA - NEET Mark": 346,
    "ST - State Rank": 14917,
    "ST - NEET Mark": 342,
  },
  {
    "College Name":
      "ST.PETERS MEDICAL COLLEGE  HOSPITAL AND RESEARCH INSTITUTE, KRISHNAGIRI",
    "College Type": "SF",
    "Quota": "GQ",
    "OC - State Rank": 3962,
    "OC - NEET Mark": 543,
    "BC - State Rank": 5407,
    "BC - NEET Mark": 517,
    "BCM - State Rank": 6053,
    "BCM - NEET Mark": 506,
    "MBC & DNC - State Rank": 6675,
    "MBC & DNC - NEET Mark": 496,
    "SC - State Rank": 12255,
    "SC - NEET Mark": 395,
    "SCA - State Rank": 14958,
    "SCA - NEET Mark": 341,
    "ST - State Rank": 16207,
    "ST - NEET Mark": 318,
  },
  {
    "College Name": "ANNAPOORNA MEDICAL COLLEGE & HOSPITAL, SALEM",
    "College Type": "SF",
    "Quota": "GQ",
    "OC - State Rank": 3971,
    "OC - NEET Mark": 543,
    "BC - State Rank": 6346,
    "BC - NEET Mark": 501,
    "BCM - State Rank": 6501,
    "BCM - NEET Mark": 499,
    "MBC & DNC - State Rank": 7321,
    "MBC & DNC - NEET Mark": 485,
    "SC - State Rank": 12336,
    "SC - NEET Mark": 393,
    "SCA - State Rank": 16157,
    "SCA - NEET Mark": 319,
  },
  {
    "College Name": "SRI MUTHUKUMARAN MEDICAL COLLEGE,CHENNAI",
    "College Type": "SF",
    "Quota": "GQ",
    "OC - State Rank": 4056,
    "OC - NEET Mark": 542,
    "BC - State Rank": 4495,
    "BC - NEET Mark": 533,
    "BCM - State Rank": 5394,
    "BCM - NEET Mark": 517,
    "MBC & DNC - State Rank": 6054,
    "MBC & DNC - NEET Mark": 506,
    "SC - State Rank": 10603,
    "SC - NEET Mark": 426,
    "SCA - State Rank": 14072,
    "SCA - NEET Mark": 358,
    "ST - State Rank": 15176,
    "ST - NEET Mark": 337,
  },
  {
    "College Name":
      "DHANALAKSHMI SRINIVASAN MEDICAL COLLEGE AND HOSPITAL, PERAMBALUR",
    "College Type": "SF",
    "Quota": "GQ",
    "OC - State Rank": 4113,
    "OC - NEET Mark": 541,
    "BC - State Rank": 4976,
    "BC - NEET Mark": 525,
    "BCM - State Rank": 5743,
    "BCM - NEET Mark": 511,
    "MBC & DNC - State Rank": 6764,
    "MBC & DNC - NEET Mark": 495,
    "SC - State Rank": 11617,
    "SC - NEET Mark": 408,
    "SCA - State Rank": 16354,
    "SCA - NEET Mark": 316,
    "ST - State Rank": 14721,
    "ST - NEET Mark": 346,
  },
  {
    "College Name": "INDIRA MEDICAL COLLEGE & HOSPITALS, THIRUVALLUR",
    "College Type": "SF",
    "Quota": "GQ",
    "OC - State Rank": 4127,
    "OC - NEET Mark": 540,
    "BC - State Rank": 6868,
    "BC - NEET Mark": 493,
    "BCM - State Rank": 7030,
    "BCM - NEET Mark": 490,
    "MBC & DNC - State Rank": 7625,
    "MBC & DNC - NEET Mark": 480,
    "SC - State Rank": 12328,
    "SC - NEET Mark": 394,
    "SCA - State Rank": 15546,
    "SCA - NEET Mark": 330,
    "ST - State Rank": 17305,
    "ST - NEET Mark": 298,
  },
  {
    "College Name": "TAGORE MEDICAL COLLEGE AND HOSPITAL, CHENNAI",
    "College Type": "SF",
    "Quota": "GQ",
    "OC - State Rank": 4313,
    "OC - NEET Mark": 537,
    "BC - State Rank": 4888,
    "BC - NEET Mark": 526,
    "BCM - State Rank": 5784,
    "BCM - NEET Mark": 511,
    "MBC & DNC - State Rank": 6313,
    "MBC & DNC - NEET Mark": 502,
    "SC - State Rank": 11083,
    "SC - NEET Mark": 417,
    "SCA - State Rank": 14479,
    "SCA - NEET Mark": 350,
    "ST - State Rank": 15327,
    "ST - NEET Mark": 334,
  },
  {
    "College Name": "ARUNAI MEDICAL COLLEGE & HOSPITAL, TIRUVANNAMALAI",
    "College Type": "SF",
    "Quota": "GQ",
    "OC - State Rank": 4317,
    "OC - NEET Mark": 537,
    "BC - State Rank": 4626,
    "BC - NEET Mark": 531,
    "BCM - State Rank": 5469,
    "BCM - NEET Mark": 516,
    "MBC & DNC - State Rank": 6025,
    "MBC & DNC - NEET Mark": 506,
    "SC - State Rank": 10767,
    "SC - NEET Mark": 423,
    "SCA - State Rank": 14483,
    "SCA - NEET Mark": 350,
    "ST - State Rank": 14673,
    "ST - NEET Mark": 347,
  },
  {
    "College Name": "MADHA MEDICAL COLLEGE AND HOSPITAL, THANDALAM, CHENNAI",
    "College Type": "SF",
    "Quota": "GQ",
    "BC - State Rank": 5658,
    "BC - NEET Mark": 513,
    "BCM - State Rank": 6763,
    "BCM - NEET Mark": 495,
    "MBC & DNC - State Rank": 7280,
    "MBC & DNC - NEET Mark": 486,
    "SC - State Rank": 11346,
    "SC - NEET Mark": 413,
    "SCA - State Rank": 15187,
    "SCA - NEET Mark": 337,
    "ST - State Rank": 16897,
    "ST - NEET Mark": 306,
  },
  {
    "College Name": "NANDHA MEDICAL COLLEGE AND HOSPITAL, PERUNDURAI, ERODE",
    "College Type": "SF",
    "Quota": "GQ",
    "BC - State Rank": 5938,
    "BC - NEET Mark": 508,
    "BCM - State Rank": 6428,
    "BCM - NEET Mark": 500,
    "MBC & DNC - State Rank": 6995,
    "MBC & DNC - NEET Mark": 491,
    "SC - State Rank": 11802,
    "SC - NEET Mark": 404,
    "SCA - State Rank": 15142,
    "SCA - NEET Mark": 338,
    "ST - State Rank": 16780,
    "ST - NEET Mark": 308,
  },
  {
    "College Name":
      "PSP MEDICAL COLLEGE HOSPITAL AND RESEARCH INSTITUTE, KANCHEEPURAM",
    "College Type": "SF",
    "Quota": "GQ",
    "BC - State Rank": 6383,
    "BC - NEET Mark": 501,
    "BCM - State Rank": 7146,
    "BCM - NEET Mark": 488,
    "MBC & DNC - State Rank": 7430,
    "MBC & DNC - NEET Mark": 483,
    "SC - State Rank": 11935,
    "SC - NEET Mark": 401,
    "SCA - State Rank": 16841,
    "SCA - NEET Mark": 307,
    "ST - State Rank": 17918,
    "ST - NEET Mark": 286,
  },
  {
    "College Name":
      "SREE MOOKAMBIKA INSTITUTE OF MEDICAL SCIENCES, KANYAKUMARI",
    "College Type": "SF",
    "Quota": "GQ",
    "BC - State Rank": 6541,
    "BC - NEET Mark": 498,
    "BCM - State Rank": 6149,
    "BCM - NEET Mark": 505,
    "MBC & DNC - State Rank": 7180,
    "MBC & DNC - NEET Mark": 488,
    "SC - State Rank": 11826,
    "SC - NEET Mark": 404,
    "SCA - State Rank": 15732,
    "SCA - NEET Mark": 327,
    "ST - State Rank": 15607,
    "ST - NEET Mark": 329,
  },
  {
    "College Name":
      "SWAMY VIVEKANANDHA MEDICAL COLLEGE HOSPITAL AND RESEARCH INSTITUTE",
    "College Type": "SF",
    "Quota": "GQ",
    "BC - State Rank": 5355,
    "BC - NEET Mark": 518,
    "BCM - State Rank": 6228,
    "BCM - NEET Mark": 503,
    "MBC & DNC - State Rank": 6725,
    "MBC & DNC - NEET Mark": 495,
    "SC - State Rank": 12228,
    "SC - NEET Mark": 395,
    "SCA - State Rank": 16546,
    "SCA - NEET Mark": 312,
    "ST - State Rank": 15194,
    "ST - NEET Mark": 337,
  },
];